// International Programs Database (clean)
const programsDatabase = {
    topTier: [{
            id: 'uwc',
            name: 'United World Colleges (UWC)',
            institution: 'UWC Network',
            description: 'Full scholarships for IB schools worldwide - transformative 2-year program with strong STEM pathway',
            type: 'study-abroad',
            cost: 'free',
            location: 'international',
            field: 'interdisciplinary',
            duration: '2 years',
            eligibility: 'Age 16+, competitive academic selection',
            dates: 'Academic year',
            financialAid: 'Full scholarships for qualified students',
            website: 'https://www.uwc.org/'
        },
        {
            id: 'yygs',
            name: 'Yale Young Global Scholars (YYGS)',
            institution: 'Yale University',
            description: 'Highly selective academic program with global cohorts and intensive seminars',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'interdisciplinary',
            duration: '2 weeks',
            eligibility: 'Rising juniors and seniors',
            dates: 'June - August',
            financialAid: 'Need-based aid available',
            website: 'https://globalscholars.yale.edu/'
        },
        {
            id: 'yyas',
            name: 'Yale Young African Scholars (YYAS)',
            institution: 'Yale University',
            description: 'Academic enrichment program for high-achieving African students',
            type: 'summer',
            cost: 'free',
            location: 'on-campus',
            field: 'interdisciplinary',
            duration: '1 week',
            eligibility: 'Students from African countries',
            dates: 'July - August',
            financialAid: 'Fully funded',
            website: 'https://globalscholars.yale.edu/yyas'
        },
        {
            id: 'rsi',
            name: 'Research Science Institute (RSI)',
            institution: 'MIT & CEE',
            description: 'Elite research program for exceptional STEM students',
            type: 'research',
            cost: 'free',
            location: 'on-campus',
            field: 'stem',
            duration: '6 weeks',
            eligibility: 'Rising seniors with strong research potential',
            dates: 'June - August',
            financialAid: 'Fully funded',
            website: 'https://www.cee.org/programs/research-science-institute'
        },
        {
            id: 'isef',
            name: 'International Science and Engineering Fair (ISEF)',
            institution: 'Society for Science',
            description: 'World’s largest pre-college science competition',
            type: 'competition',
            cost: 'free',
            location: 'international',
            field: 'stem',
            duration: '1 week',
            eligibility: 'Qualify through affiliated fairs',
            dates: 'May annually',
            financialAid: 'Travel support for finalists',
            website: 'https://www.societyforscience.org/isef/'
        },
        {
            id: 'earth-prize',
            name: 'The Earth Prize',
            institution: 'The Earth Prize',
            description: 'Global environmental sustainability competition for teens',
            type: 'competition',
            cost: 'free',
            location: 'international',
            field: 'interdisciplinary',
            duration: 'Project-based',
            eligibility: 'Ages 13-19',
            dates: 'Annual cycle',
            financialAid: 'Cash awards for winners',
            website: 'https://www.theearthprize.org/'
        },
        {
            id: 'ieee-yesist12',
            name: 'IEEE YESIST12',
            institution: 'IEEE',
            description: 'Global innovation and technology competition for students',
            type: 'competition',
            cost: 'free',
            location: 'international',
            field: 'stem',
            duration: 'Multi-stage',
            eligibility: 'High school and university students',
            dates: 'Annual',
            financialAid: 'Awards and recognition',
            website: 'https://yesist12.ieee.org/'
        },
        {
            id: 'ieee-tryengineering',
            name: 'IEEE TryEngineering Summer Institutes',
            institution: 'IEEE',
            description: 'Engineering-focused summer programs hosted at universities',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'stem',
            duration: '1-2 weeks',
            eligibility: 'High school students',
            dates: 'Summer sessions',
            financialAid: 'Scholarships may be available',
            website: 'https://tryengineering.org/'
        },
        {
            id: 'tasp',
            name: 'Telluride Association Summer Program (TASP)',
            institution: 'Telluride Association',
            description: 'Free academic program focused on seminar-style learning',
            type: 'summer',
            cost: 'free',
            location: 'on-campus',
            field: 'interdisciplinary',
            duration: '6 weeks',
            eligibility: 'Rising seniors',
            dates: 'June - July',
            financialAid: 'Fully funded',
            website: 'https://www.tellurideassociation.org/our-programs/high-school-students/tasp/'
        },
        {
            id: 'ssp',
            name: 'Summer Science Program (SSP)',
            institution: 'Summer Science Program',
            description: 'Research-focused program in astrophysics or biochemistry',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'stem',
            duration: '39 days',
            eligibility: 'Rising seniors',
            dates: 'June - July',
            financialAid: 'Need-based aid available',
            website: 'https://summerscience.org/'
        },
        {
            id: 'promys',
            name: 'PROMYS',
            institution: 'Boston University',
            description: 'Immersive mathematics program emphasizing discovery and proof',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'stem',
            duration: '6 weeks',
            eligibility: 'Ages 14-18',
            dates: 'July - August',
            financialAid: 'Aid available',
            website: 'https://promys.org/'
        },
        {
            id: 'ross',
            name: 'Ross Mathematics Program',
            institution: 'Ross Program',
            description: 'Intensive number theory program for advanced students',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'stem',
            duration: '6 weeks',
            eligibility: 'Ages 15-18',
            dates: 'June - July',
            financialAid: 'Aid available',
            website: 'https://rossprogram.org/'
        },
        {
            id: 'mites',
            name: 'MITES',
            institution: 'MIT',
            description: 'Free STEM enrichment program for underrepresented students',
            type: 'summer',
            cost: 'free',
            location: 'on-campus',
            field: 'stem',
            duration: '6 weeks',
            eligibility: 'Rising seniors',
            dates: 'June - August',
            financialAid: 'Fully funded',
            website: 'https://oeop.mit.edu/programs/mites'
        },
        {
            id: 'bwsi',
            name: 'MIT Beaver Works Summer Institute (BWSI)',
            institution: 'MIT',
            description: 'Rigorous STEM summer program with project-based courses',
            type: 'summer',
            cost: 'free',
            location: 'on-campus',
            field: 'stem',
            duration: '4 weeks',
            eligibility: 'Rising seniors',
            dates: 'July',
            financialAid: 'Free',
            website: 'https://beaverworks.ll.mit.edu/CMS/bw/bwsi'
        },
        {
            id: 'simons-summer',
            name: 'Simons Summer Research Program',
            institution: 'Stony Brook University',
            description: 'Mentored research program for high-achieving students',
            type: 'research',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'stem',
            duration: '7 weeks',
            eligibility: 'Rising seniors',
            dates: 'June - August',
            financialAid: 'Stipend and aid available',
            website: 'https://www.stonybrook.edu/commcms/simons/'
        },
        {
            id: 'regeneron-sts',
            name: 'Regeneron Science Talent Search',
            institution: 'Society for Science',
            description: 'Prestigious research competition for high school seniors',
            type: 'competition',
            cost: 'free',
            location: 'on-campus',
            field: 'stem',
            duration: 'Finals week',
            eligibility: 'High school seniors',
            dates: 'March finals',
            financialAid: 'Scholarships and awards',
            website: 'https://www.societyforscience.org/regeneron-sts/'
        },
        {
            id: 'usamo',
            name: 'USA Mathematical Olympiad (USAMO)',
            institution: 'MAA',
            description: 'Top-level math competition in the United States',
            type: 'competition',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: '2 days',
            eligibility: 'Qualify through AMC/AIME',
            dates: 'April',
            financialAid: 'Free',
            website: 'https://www.maa.org/math-competitions/usamo'
        },
        {
            id: 'usaco-platinum',
            name: 'USA Computing Olympiad (USACO) - Platinum',
            institution: 'USACO',
            description: 'Highest division of the USACO programming contest',
            type: 'competition',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'Seasonal contests',
            eligibility: 'High school students',
            dates: 'December - March',
            financialAid: 'Free',
            website: 'http://www.usaco.org/'
        },
        {
            id: 'imo',
            name: 'International Mathematical Olympiad (IMO)',
            institution: 'IMU',
            description: 'Most prestigious global math competition for high school students',
            type: 'competition',
            cost: 'free',
            location: 'international',
            field: 'stem',
            duration: '2 days',
            eligibility: 'National team selection',
            dates: 'July',
            financialAid: 'Delegation-funded',
            website: 'https://www.imo-official.org/'
        },
        {
            id: 'ipho',
            name: 'International Physics Olympiad (IPhO)',
            institution: 'IPhO',
            description: 'Global physics competition for secondary students',
            type: 'competition',
            cost: 'free',
            location: 'international',
            field: 'stem',
            duration: '1 week',
            eligibility: 'National team selection',
            dates: 'July',
            financialAid: 'Delegation-funded',
            website: 'https://www.ipho-new.org/'
        },
        {
            id: 'icho',
            name: 'International Chemistry Olympiad (IChO)',
            institution: 'IChO',
            description: 'Global chemistry competition for secondary students',
            type: 'competition',
            cost: 'free',
            location: 'international',
            field: 'stem',
            duration: '10 days',
            eligibility: 'National team selection',
            dates: 'July',
            financialAid: 'Delegation-funded',
            website: 'https://www.icho-official.org/'
        },
        {
            id: 'ibo',
            name: 'International Biology Olympiad (IBO)',
            institution: 'IBO',
            description: 'Top biology competition for high school students worldwide',
            type: 'competition',
            cost: 'free',
            location: 'international',
            field: 'stem',
            duration: '1 week',
            eligibility: 'National team selection',
            dates: 'July',
            financialAid: 'Delegation-funded',
            website: 'https://www.ibo-info.org/'
        },
        {
            id: 'ioi',
            name: 'International Olympiad in Informatics (IOI)',
            institution: 'IOI',
            description: 'Premier programming competition for students worldwide',
            type: 'competition',
            cost: 'free',
            location: 'international',
            field: 'stem',
            duration: '2 contest days',
            eligibility: 'National team selection',
            dates: 'July - August',
            financialAid: 'Delegation-funded',
            website: 'https://ioinformatics.org/'
        },
        {
            id: 'ioaa',
            name: 'International Olympiad on Astronomy & Astrophysics (IOAA)',
            institution: 'IOAA',
            description: 'Global astronomy competition with theory and observational rounds',
            type: 'competition',
            cost: 'free',
            location: 'international',
            field: 'stem',
            duration: '1 week',
            eligibility: 'National team selection',
            dates: 'August',
            financialAid: 'Delegation-funded',
            website: 'http://www.ioaa.info/'
        },
        {
            id: 'igem-hs',
            name: 'iGEM High School Division',
            institution: 'iGEM Foundation',
            description: 'Synthetic biology competition with research and project development',
            type: 'competition',
            cost: 'paid-aid',
            location: 'international',
            field: 'stem',
            duration: 'Full season',
            eligibility: 'High school teams',
            dates: 'Seasonal',
            financialAid: 'Grants available',
            website: 'https://igem.org/'
        },
        {
            id: 'first-global',
            name: 'FIRST Global Challenge',
            institution: 'FIRST Global',
            description: 'International robotics competition with national teams',
            type: 'competition',
            cost: 'free',
            location: 'international',
            field: 'stem',
            duration: '1 week',
            eligibility: 'National team selection',
            dates: 'October',
            financialAid: 'Delegation-funded',
            website: 'https://first.global/'
        },
        {
            id: 'breakthrough-junior',
            name: 'Breakthrough Junior Challenge',
            institution: 'Breakthrough Prize Foundation',
            description: 'Global science video competition with significant scholarship prizes',
            type: 'competition',
            cost: 'free',
            location: 'international',
            field: 'stem',
            duration: 'Submission-based',
            eligibility: 'Ages 13-18',
            dates: 'Annual',
            financialAid: 'Scholarship awards',
            website: 'https://breakthroughjuniorchallenge.org/'
        },
        {
            id: 'rise-global',
            name: 'Rise Global Challenge',
            institution: 'Rise',
            description: 'Global talent search for young people with academic and service excellence',
            type: 'competition',
            cost: 'free',
            location: 'international',
            field: 'interdisciplinary',
            duration: 'Application-based',
            eligibility: 'Ages 15-17',
            dates: 'Annual',
            financialAid: 'Full scholarship support',
            website: 'https://www.risefortheworld.org/'
        },
        {
            id: 'pioneer-academics',
            name: 'Pioneer Academics',
            institution: 'Pioneer Academics',
            description: 'Online university-level research program with faculty mentorship',
            type: 'research',
            cost: 'paid-aid',
            location: 'online',
            field: 'interdisciplinary',
            duration: '8-12 weeks',
            eligibility: 'Grades 9-12',
            dates: 'Multiple terms',
            financialAid: 'Limited aid available',
            website: 'https://pioneeracademics.com/'
        },
        {
            id: 'lumiere-research',
            name: 'Lumiere Research Scholar Program',
            institution: 'Lumiere Education',
            description: 'Selective research mentorship program with PhD researchers for advanced STEM students',
            type: 'research',
            cost: 'paid-aid',
            location: 'online',
            field: 'stem',
            duration: '12 weeks',
            eligibility: 'Advanced high school students (grades 10-12)',
            dates: 'Multiple cohorts throughout year',
            financialAid: 'Need-based aid available',
            website: 'https://www.lumiere-education.com/'
        },
        {
            id: 'polygence',
            name: 'Polygence',
            institution: 'Polygence',
            description: 'Flexible research projects in STEM and humanities with PhD-level mentorship',
            type: 'research',
            cost: 'paid-aid',
            location: 'online',
            field: 'interdisciplinary',
            duration: '6-12 weeks',
            eligibility: 'High school students grades 9-12',
            dates: 'Multiple start dates',
            financialAid: 'Scholarship opportunities available',
            website: 'https://www.polygence.org/'
        },
        {
            id: 'nasa-internship',
            name: 'NASA Internships',
            institution: 'NASA',
            description: 'Selective internship programs with opportunities for international students on specific tracks',
            type: 'internship',
            cost: 'paid',
            location: 'on-campus',
            field: 'stem',
            duration: 'Summer/semester',
            eligibility: 'High school seniors and undergraduates',
            dates: 'Summer and semester programs',
            financialAid: 'Paid internships (limited international availability)',
            website: 'https://internships.nasa.gov/'
        },
        {
            id: 'luriere-research',
            name: 'Lumiere Research Scholar Program',
            institution: 'Lumiere Education',
            description: 'Selective research mentorship program with PhD researchers for advanced STEM students',
            type: 'research',
            cost: 'paid-aid',
            location: 'online',
            field: 'stem',
            duration: '12 weeks',
            eligibility: 'Advanced high school students (grades 10-12)',
            dates: 'Multiple cohorts throughout year',
            financialAid: 'Need-based aid available',
            website: 'https://www.lumiere-education.com/'
        },
        {
            id: 'conrad-challenge',
            name: 'Conrad Challenge',
            institution: 'Conrad Foundation',
            description: 'Innovation challenge for global student teams',
            type: 'competition',
            cost: 'free',
            location: 'international',
            field: 'interdisciplinary',
            duration: 'Multi-phase',
            eligibility: 'Ages 13-18',
            dates: 'Annual',
            financialAid: 'Prizes and mentorship',
            website: 'https://www.conradchallenge.org/'
        }
    ],
    achievable: [{
            id: 'pioneer-academics',
            name: 'Pioneer Academics',
            institution: 'Pioneer Academics',
            description: 'Online university-level research program with faculty mentorship for high school students',
            type: 'research',
            cost: 'paid-aid',
            location: 'online',
            field: 'interdisciplinary',
            duration: '8-12 weeks',
            eligibility: 'Grades 9-12',
            dates: 'Multiple terms throughout year',
            financialAid: 'Limited aid available',
            website: 'https://pioneeracademics.com/'
        },
        {
            id: 'girls-who-code',
            name: 'Girls Who Code',
            institution: 'Girls Who Code',
            description: 'Coding programs, summer camps, and scholarships with global recognition and alumnae network',
            type: 'summer',
            cost: 'free',
            location: 'on-campus',
            field: 'stem',
            duration: '7 weeks',
            eligibility: 'High school girls grades 9-12',
            dates: 'Summer programs',
            financialAid: 'Free, scholarships available',
            website: 'https://girlswhocode.com/'
        },
        {
            id: 'technovation-girls',
            name: 'Technovation Girls',
            institution: 'Iridescent',
            description: 'Girls build tech solutions to real-world problems with mentorship - strong for university applications',
            type: 'competition',
            cost: 'free',
            location: 'hybrid',
            field: 'stem',
            duration: '5 months',
            eligibility: 'Girls ages 10-18',
            dates: 'September - April',
            financialAid: 'Free program',
            website: 'https://technovationchallenge.org/'
        },
        {
            id: 'girls-in-tech',
            name: 'Girls in Tech',
            institution: 'Girls in Tech',
            description: 'Community events, mentorship, and scholarships promoting women in technology',
            type: 'community',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'Ongoing',
            eligibility: 'Women in tech worldwide',
            dates: 'Year-round',
            financialAid: 'Scholarships and events',
            website: 'https://girlsintech.org/'
        },
        {
            id: 'women-techmakers',
            name: 'Women Techmakers',
            institution: 'Google',
            description: 'Google-backed community with events, resources, and scholarships for women in technology',
            type: 'community',
            cost: 'free',
            location: 'hybrid',
            field: 'stem',
            duration: 'Ongoing',
            eligibility: 'Women interested in tech',
            dates: 'Year-round',
            financialAid: 'Scholarships and grants available',
            website: 'https://www.womentechmakers.com/'
        },
        {
            id: 'african-leadership-academy',
            name: 'African Leadership Academy',
            institution: 'African Leadership Academy',
            description: 'Intensive STEM and leadership program designed for African students with strong scientific focus',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'stem',
            duration: '4-6 weeks',
            eligibility: 'African high school students',
            dates: 'Summer programs',
            financialAid: 'Scholarships available',
            website: 'https://www.africaleadership.org/'
        },
        {
            id: 'afs-global-stem',
            name: 'AFS Global STEM Academies',
            institution: 'AFS Intercultural Programs',
            description: 'International STEM academy experiences and cultural exchanges with host families',
            type: 'study-abroad',
            cost: 'paid-aid',
            location: 'international',
            field: 'stem',
            duration: '2-3 weeks',
            eligibility: 'High school students',
            dates: 'Summer programs',
            financialAid: 'Scholarships available',
            website: 'https://www.afs.org/'
        },
        {
            id: 'nyu-abu-dhabi-global',
            name: 'NYU Abu Dhabi Global Scholarship',
            institution: 'NYU Abu Dhabi',
            description: 'Full funding opportunity for undergraduate study - very strong for Egyptian STEM students',
            type: 'study-abroad',
            cost: 'free',
            location: 'on-campus',
            field: 'stem',
            duration: '4 years',
            eligibility: 'International high school graduates with strong academics',
            dates: 'Academic year',
            financialAid: 'Full scholarship including living expenses',
            website: 'https://nyuad.nyu.edu/en/admissions/how-to-apply/international-applicants/'
        },
        {
            id: 'kaust-gifted',
            name: 'KAUST Gifted Student Program',
            institution: 'KAUST',
            description: 'Summer program for advanced STEM students from MENA region with scholarships',
            type: 'summer',
            cost: 'free',
            location: 'on-campus',
            field: 'stem',
            duration: '4-6 weeks',
            eligibility: 'High school students from Middle East/North Africa',
            dates: 'Summer program',
            financialAid: 'Fully funded',
            website: 'https://www.kaust.edu.sa/'
        },
        {
            id: 'eth-zurich-excellence',
            name: 'ETH Zurich Excellence Scholarship',
            institution: 'ETH Zurich',
            description: 'Full scholarship for outstanding international students to pursue engineering/science degrees',
            type: 'study-abroad',
            cost: 'free',
            location: 'on-campus',
            field: 'stem',
            duration: '3-4 years',
            eligibility: 'International high school graduates with exceptional STEM credentials',
            dates: 'Academic year',
            financialAid: 'Full scholarship',
            website: 'https://www.ethz.ch/en/studies/financial-support-and-funding/scholarships/eth-zurich-excellence-scholarship.html'
        },
        {
            id: 'harvard-precollege',
            name: 'Harvard Pre-College Program',
            institution: 'Harvard University',
            description: 'College-level courses for high school students on campus',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'interdisciplinary',
            duration: '2-7 weeks',
            eligibility: 'Rising juniors and seniors',
            dates: 'June - August',
            financialAid: 'Need-based aid',
            website: 'https://summer.harvard.edu/high-school-programs/'
        },
        {
            id: 'columbia-summer',
            name: 'Columbia Summer Programs',
            institution: 'Columbia University',
            description: 'Academic programs for high school students in NYC',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'interdisciplinary',
            duration: '2-3 weeks',
            eligibility: 'High school students',
            dates: 'June - August',
            financialAid: 'Some aid available',
            website: 'https://sps.columbia.edu/highschool'
        },
        {
            id: 'upenn-summer',
            name: 'Penn Summer Academies',
            institution: 'University of Pennsylvania',
            description: 'Thematic summer programs across disciplines',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'interdisciplinary',
            duration: '3 weeks',
            eligibility: 'Rising juniors and seniors',
            dates: 'July',
            financialAid: 'Financial aid available',
            website: 'https://www.sas.upenn.edu/summer/programs/high-school'
        },
        {
            id: 'world-scholars-cup',
            name: 'World Scholar’s Cup',
            institution: 'World Scholar’s Cup',
            description: 'International academic tournament with regional and global rounds',
            type: 'competition',
            cost: 'paid-aid',
            location: 'international',
            field: 'interdisciplinary',
            duration: 'Regional + global rounds',
            eligibility: 'Ages 8-18',
            dates: 'Year-round',
            financialAid: 'Fee waivers available',
            website: 'https://www.scholarscup.org/'
        },
        {
            id: 'genius-olympiad',
            name: 'Genius Olympiad',
            institution: 'Genius Olympiad',
            description: 'International competition for environmental and science projects',
            type: 'competition',
            cost: 'free',
            location: 'international',
            field: 'stem',
            duration: '1 week finals',
            eligibility: 'High school students',
            dates: 'June',
            financialAid: 'Scholarships available',
            website: 'https://www.geniusolympiad.org/'
        },
        {
            id: 'brown-precollege',
            name: 'Brown Pre-College Programs',
            institution: 'Brown University',
            description: 'Pre-college summer programs and courses',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'interdisciplinary',
            duration: '1-6 weeks',
            eligibility: 'High school students',
            dates: 'June - August',
            financialAid: 'Need-based aid',
            website: 'https://precollege.brown.edu/'
        },
        {
            id: 'cornell-summer',
            name: 'Cornell Summer College',
            institution: 'Cornell University',
            description: 'Pre-college summer courses on campus',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'interdisciplinary',
            duration: '2-6 weeks',
            eligibility: 'High school students',
            dates: 'June - August',
            financialAid: 'Financial aid available',
            website: 'https://sce.cornell.edu/sc/'
        },
        {
            id: 'stanford-precollegiate',
            name: 'Stanford Pre-Collegiate Summer Institutes',
            institution: 'Stanford University',
            description: 'Advanced summer courses for high school students',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'interdisciplinary',
            duration: '2-4 weeks',
            eligibility: 'High school students',
            dates: 'June - August',
            financialAid: 'Limited aid available',
            website: 'https://spcs.stanford.edu/programs/high-school'
        },
        {
            id: 'ucla-summer',
            name: 'UCLA Summer Programs for High School Students',
            institution: 'UCLA',
            description: 'Pre-college courses and enrichment programs',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'interdisciplinary',
            duration: '2-6 weeks',
            eligibility: 'High school students',
            dates: 'June - August',
            financialAid: 'Some aid available',
            website: 'https://www.summer.ucla.edu/'
        },
        {
            id: 'berkeley-summer',
            name: 'UC Berkeley Pre-College Scholars',
            institution: 'UC Berkeley',
            description: 'College courses and residential experience',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'interdisciplinary',
            duration: '2-6 weeks',
            eligibility: 'High school students',
            dates: 'June - August',
            financialAid: 'Limited aid available',
            website: 'https://precollege.berkeley.edu/'
        },
        {
            id: 'nyu-precollege',
            name: 'NYU Precollege',
            institution: 'New York University',
            description: 'University-level courses and campus experience',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'interdisciplinary',
            duration: '6 weeks',
            eligibility: 'High school students',
            dates: 'June - August',
            financialAid: 'Limited aid available',
            website: 'https://www.nyu.edu/admissions/high-school-and-middle-school-programs/high-school-programs/precollege.html'
        },
        {
            id: 'georgetown-precollege',
            name: 'Georgetown Pre-College Programs',
            institution: 'Georgetown University',
            description: 'Intensive summer courses in DC',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'interdisciplinary',
            duration: '1-3 weeks',
            eligibility: 'High school students',
            dates: 'June - August',
            financialAid: 'Some aid available',
            website: 'https://summer.georgetown.edu/programs-courses/high-school-students/'
        },
        {
            id: 'duke-tip',
            name: 'Duke TIP Summer Studies',
            institution: 'Duke University',
            description: 'Academic summer programs for gifted students',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'interdisciplinary',
            duration: '2-3 weeks',
            eligibility: 'Grades 7-11',
            dates: 'June - July',
            financialAid: 'Aid available',
            website: 'https://tip.duke.edu/'
        },
        {
            id: 'jhu-cty',
            name: 'Johns Hopkins CTY Summer Programs',
            institution: 'Johns Hopkins University',
            description: 'Summer programs for advanced students',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'interdisciplinary',
            duration: '3 weeks',
            eligibility: 'Grades 2-12',
            dates: 'June - August',
            financialAid: 'Financial aid available',
            website: 'https://cty.jhu.edu/'
        },
        {
            id: 'northwestern-ctd',
            name: 'Northwestern CTD Summer Programs',
            institution: 'Northwestern University',
            description: 'Programs for academically talented students',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'interdisciplinary',
            duration: '3 weeks',
            eligibility: 'Grades 3-12',
            dates: 'June - August',
            financialAid: 'Scholarships available',
            website: 'https://www.ctd.northwestern.edu/'
        },
        {
            id: 'cmu-sams',
            name: 'Carnegie Mellon SAMS',
            institution: 'Carnegie Mellon University',
            description: 'STEM program for underrepresented students',
            type: 'summer',
            cost: 'free',
            location: 'on-campus',
            field: 'stem',
            duration: '6 weeks',
            eligibility: 'Rising seniors',
            dates: 'June - August',
            financialAid: 'Fully funded',
            website: 'https://www.cmu.edu/pre-college/academic-programs/sams.html'
        },
        {
            id: 'smith-ssep',
            name: 'Smith College SSEP',
            institution: 'Smith College',
            description: 'Science and engineering program for young women',
            type: 'research',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'stem',
            duration: '4 weeks',
            eligibility: 'Rising seniors (women)',
            dates: 'July',
            financialAid: 'Generous aid available',
            website: 'https://www.smith.edu/academics/summer-science-engineering-program'
        },
        {
            id: 'tufts-summit',
            name: 'Tufts Summer Programs',
            institution: 'Tufts University',
            description: 'Pre-college programs in multiple subjects',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'interdisciplinary',
            duration: '2-3 weeks',
            eligibility: 'High school students',
            dates: 'July',
            financialAid: 'Aid available',
            website: 'https://ase.tufts.edu/summer/'
        },
        {
            id: 'boston-leadership',
            name: 'Boston Leadership Institute',
            institution: 'BLI',
            description: 'Pre-college programs in STEM and business',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'interdisciplinary',
            duration: '1-3 weeks',
            eligibility: 'High school students',
            dates: 'June - August',
            financialAid: 'Merit scholarships',
            website: 'https://www.bostonleadershipinstitute.com/'
        },
        {
            id: 'oxford-summer',
            name: 'Oxford Summer Courses',
            institution: 'Oxford Summer Courses',
            description: 'Academic summer courses at Oxford',
            type: 'summer',
            cost: 'paid-aid',
            location: 'international',
            field: 'interdisciplinary',
            duration: '2 weeks',
            eligibility: 'Ages 13-18',
            dates: 'June - August',
            financialAid: 'Limited aid',
            website: 'https://www.oxfordsummercourses.com/'
        },
        {
            id: 'cambridge-summer',
            name: 'Cambridge Immerse',
            institution: 'Immerse Education',
            description: 'Pre-college programs in Cambridge',
            type: 'summer',
            cost: 'paid-aid',
            location: 'international',
            field: 'interdisciplinary',
            duration: '2 weeks',
            eligibility: 'Ages 13-18',
            dates: 'June - August',
            financialAid: 'Scholarships available',
            website: 'https://www.immerse.education/'
        },
        {
            id: 'imperial-precollege',
            name: 'Imperial College London Pre-College',
            institution: 'Imperial College London',
            description: 'STEM-focused pre-college programs in London',
            type: 'summer',
            cost: 'paid-aid',
            location: 'international',
            field: 'stem',
            duration: '2 weeks',
            eligibility: 'Ages 16-18',
            dates: 'June - August',
            financialAid: 'Limited aid',
            website: 'https://www.imperial.ac.uk/study/visit/pre-college/'
        },
        {
            id: 'lse-summer',
            name: 'LSE Summer School',
            institution: 'London School of Economics',
            description: 'Economics and social science courses',
            type: 'summer',
            cost: 'paid-aid',
            location: 'international',
            field: 'humanities',
            duration: '3-6 weeks',
            eligibility: 'High school seniors and graduates',
            dates: 'June - August',
            financialAid: 'Limited aid',
            website: 'https://www.lse.ac.uk/study-at-lse/Summer-Schools'
        },
        {
            id: 'afsd',
            name: 'AFS Intercultural Programs',
            institution: 'AFS',
            description: 'International exchange and study abroad programs',
            type: 'summer',
            cost: 'paid-aid',
            location: 'international',
            field: 'interdisciplinary',
            duration: 'Summer to year-long',
            eligibility: 'High school students',
            dates: 'Multiple cycles',
            financialAid: 'Scholarships available',
            website: 'https://www.afs.org/'
        },
        {
            id: 'nslc',
            name: 'National Student Leadership Conference (NSLC)',
            institution: 'NSLC',
            description: 'Leadership programs in medicine, engineering, and business',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'interdisciplinary',
            duration: '1-3 weeks',
            eligibility: 'High school students',
            dates: 'Summer sessions',
            financialAid: 'Limited aid',
            website: 'https://www.nslcleaders.org/'
        },
        {
            id: 'launchx',
            name: 'LaunchX',
            institution: 'LaunchX',
            description: 'Entrepreneurship program for high school students',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'interdisciplinary',
            duration: '3-4 weeks',
            eligibility: 'High school students',
            dates: 'Summer sessions',
            financialAid: 'Scholarships available',
            website: 'https://www.launchx.com/'
        },
        {
            id: 'wharton-global-youth',
            name: 'Wharton Global Youth Program',
            institution: 'University of Pennsylvania',
            description: 'Business and finance programs for high school students',
            type: 'summer',
            cost: 'paid-aid',
            location: 'on-campus',
            field: 'interdisciplinary',
            duration: '2-6 weeks',
            eligibility: 'High school students',
            dates: 'June - August',
            financialAid: 'Some aid available',
            website: 'https://globalyouth.wharton.upenn.edu/'
        },
        {
            id: 'mit-launch',
            name: 'MIT Launch',
            institution: 'MIT LaunchX',
            description: 'Entrepreneurship and innovation program',
            type: 'summer',
            cost: 'paid-aid',
            location: 'online',
            field: 'interdisciplinary',
            duration: '3 months',
            eligibility: 'High school students',
            dates: 'Summer',
            financialAid: 'Limited aid',
            website: 'https://launchx.com/'
        },
        {
            id: 'ai4all',
            name: 'AI4ALL Summer Programs',
            institution: 'AI4ALL',
            description: 'AI-focused summer programs for high school students',
            type: 'summer',
            cost: 'paid-aid',
            location: 'online',
            field: 'stem',
            duration: '2-3 weeks',
            eligibility: 'High school students',
            dates: 'Summer',
            financialAid: 'Scholarships available',
            website: 'https://ai-4-all.org/'
        },
        {
            id: 'technovation',
            name: 'Technovation Girls',
            institution: 'Technovation',
            description: 'Global tech entrepreneurship program for girls',
            type: 'competition',
            cost: 'free',
            location: 'international',
            field: 'stem',
            duration: 'Seasonal',
            eligibility: 'Girls ages 8-18',
            dates: 'Annual season',
            financialAid: 'Free',
            website: 'https://technovationchallenge.org/'
        },
        {
            id: 'diamond-challenge',
            name: 'Diamond Challenge',
            institution: 'University of Delaware',
            description: 'Entrepreneurship competition for high school teams',
            type: 'competition',
            cost: 'free',
            location: 'international',
            field: 'interdisciplinary',
            duration: 'Multi-phase',
            eligibility: 'High school students',
            dates: 'Annual',
            financialAid: 'Prizes awarded',
            website: 'https://diamondchallenge.org/'
        },
        {
            id: 'hosa',
            name: 'HOSA Global & National Conferences',
            institution: 'HOSA',
            description: 'Health science competitive events and leadership',
            type: 'competition',
            cost: 'paid-aid',
            location: 'international',
            field: 'stem',
            duration: 'Seasonal',
            eligibility: 'Members grades 6-12',
            dates: 'Year-round',
            financialAid: 'Varies by chapter',
            website: 'https://hosa.org/'
        },
        {
            id: 'deca',
            name: 'DECA International Career Development Conference',
            institution: 'DECA',
            description: 'Business and marketing competitions for students',
            type: 'competition',
            cost: 'paid-aid',
            location: 'international',
            field: 'interdisciplinary',
            duration: 'Seasonal',
            eligibility: 'High school members',
            dates: 'April',
            financialAid: 'Varies by chapter',
            website: 'https://www.deca.org/'
        },
        {
            id: 'model-un',
            name: 'Model United Nations Conferences',
            institution: 'Various',
            description: 'Global MUN conferences focused on diplomacy and policy',
            type: 'competition',
            cost: 'paid-aid',
            location: 'international',
            field: 'humanities',
            duration: '2-4 days',
            eligibility: 'High school students',
            dates: 'Year-round',
            financialAid: 'Fee waivers vary',
            website: 'https://www.una-usa.org/global-classrooms'
        }
    ],
    accessible: [{
            id: 'cs50',
            name: 'Harvard CS50',
            institution: 'Harvard University',
            description: 'Free introductory computer science course with global community',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'Self-paced (12 weeks suggested)',
            eligibility: 'Open to all',
            dates: 'Enroll anytime',
            financialAid: 'Free',
            website: 'https://cs50.harvard.edu/'
        },
        {
            id: 'khan-academy',
            name: 'Khan Academy',
            institution: 'Khan Academy',
            description: 'Free math, science, and humanities courses',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'interdisciplinary',
            duration: 'Self-paced',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://www.khanacademy.org/'
        },
        {
            id: 'edx',
            name: 'edX',
            institution: 'edX',
            description: 'Free online courses from top universities',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'interdisciplinary',
            duration: 'Varies',
            eligibility: 'Open to all',
            dates: 'Rolling',
            financialAid: 'Audit for free',
            website: 'https://www.edx.org/'
        },
        {
            id: 'coursera',
            name: 'Coursera',
            institution: 'Coursera',
            description: 'University courses with financial aid options',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'interdisciplinary',
            duration: 'Varies',
            eligibility: 'Open to all',
            dates: 'Rolling enrollment',
            financialAid: 'Financial aid available',
            website: 'https://www.coursera.org/'
        },
        {
            id: 'ieee-explore',
            name: 'IEEE Student Activities & Challenges',
            institution: 'IEEE',
            description: 'Student challenges, resources, and engineering activities',
            type: 'competition',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'Varies',
            eligibility: 'Students worldwide',
            dates: 'Year-round',
            financialAid: 'Free participation in many events',
            website: 'https://www.ieee.org/education/students.html'
        },
        {
            id: 'mit-ocw',
            name: 'MIT OpenCourseWare',
            institution: 'MIT',
            description: 'Free MIT course materials for self-study',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'interdisciplinary',
            duration: 'Self-paced',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://ocw.mit.edu/'
        },
        {
            id: 'futurelearn',
            name: 'FutureLearn',
            institution: 'FutureLearn',
            description: 'Free online courses from global universities',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'interdisciplinary',
            duration: 'Varies',
            eligibility: 'Open to all',
            dates: 'Rolling',
            financialAid: 'Audit for free',
            website: 'https://www.futurelearn.com/'
        },
        {
            id: 'udacity',
            name: 'Udacity Free Courses',
            institution: 'Udacity',
            description: 'Free technology and programming courses',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'Self-paced',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free courses available',
            website: 'https://www.udacity.com/'
        },
        {
            id: 'codecademy',
            name: 'Codecademy',
            institution: 'Codecademy',
            description: 'Interactive coding lessons and projects',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'Self-paced',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free tier available',
            website: 'https://www.codecademy.com/'
        },
        {
            id: 'freecodecamp',
            name: 'freeCodeCamp',
            institution: 'freeCodeCamp',
            description: 'Free coding curriculum with certifications',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'Self-paced',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://www.freecodecamp.org/'
        },
        {
            id: 'brilliant',
            name: 'Brilliant',
            institution: 'Brilliant',
            description: 'Interactive STEM problem-solving courses',
            type: 'summer',
            cost: 'paid-aid',
            location: 'online',
            field: 'stem',
            duration: 'Self-paced',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free trial available',
            website: 'https://brilliant.org/'
        },
        {
            id: 'scratch',
            name: 'Scratch',
            institution: 'MIT Media Lab',
            description: 'Beginner-friendly visual programming platform',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'Self-paced',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://scratch.mit.edu/'
        },
        {
            id: 'tinkercad',
            name: 'Tinkercad',
            institution: 'Autodesk',
            description: 'Free 3D design, electronics, and coding platform',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'Self-paced',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://www.tinkercad.com/'
        },
        {
            id: 'arduino',
            name: 'Arduino Project Hub',
            institution: 'Arduino',
            description: 'Electronics and programming tutorials',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'Project-based',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://create.arduino.cc/'
        },
        {
            id: 'raspberry-pi',
            name: 'Raspberry Pi Projects',
            institution: 'Raspberry Pi Foundation',
            description: 'Hands-on computing and electronics projects',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'Project-based',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://projects.raspberrypi.org/'
        },
        {
            id: 'desmos',
            name: 'Desmos',
            institution: 'Desmos',
            description: 'Free graphing calculator and activities',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'On-demand',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://www.desmos.com/'
        },
        {
            id: 'phet',
            name: 'PhET Interactive Simulations',
            institution: 'University of Colorado Boulder',
            description: 'Interactive science and math simulations',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'On-demand',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://phet.colorado.edu/'
        },
        {
            id: 'geogebra',
            name: 'GeoGebra',
            institution: 'GeoGebra',
            description: 'Free interactive mathematics software',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'Self-paced',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://www.geogebra.org/'
        },
        {
            id: 'wolframalpha',
            name: 'Wolfram|Alpha',
            institution: 'Wolfram Research',
            description: 'Computational knowledge engine for STEM',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'On-demand',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free basic version',
            website: 'https://www.wolframalpha.com/'
        },
        {
            id: 'project-euler',
            name: 'Project Euler',
            institution: 'Project Euler',
            description: 'Math and programming challenge problems',
            type: 'competition',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'Self-paced',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://projecteuler.net/'
        },
        {
            id: 'codeforces',
            name: 'Codeforces',
            institution: 'Codeforces',
            description: 'Competitive programming contests and practice',
            type: 'competition',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'Regular contests',
            eligibility: 'Open to all',
            dates: 'Weekly contests',
            financialAid: 'Free',
            website: 'https://codeforces.com/'
        },
        {
            id: 'hackerrank',
            name: 'HackerRank',
            institution: 'HackerRank',
            description: 'Programming practice and competitions',
            type: 'competition',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'Self-paced + contests',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://www.hackerrank.com/'
        },
        {
            id: 'leetcode',
            name: 'LeetCode',
            institution: 'LeetCode',
            description: 'Coding practice and interview preparation',
            type: 'competition',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'Self-paced',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free tier available',
            website: 'https://leetcode.com/'
        },
        {
            id: 'codewars',
            name: 'Codewars',
            institution: 'Codewars',
            description: 'Programming challenges and skill progression',
            type: 'competition',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'Self-paced',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://www.codewars.com/'
        },
        {
            id: 'kaggle-learn',
            name: 'Kaggle Learn',
            institution: 'Kaggle',
            description: 'Free data science micro-courses',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'Self-paced',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://www.kaggle.com/learn'
        },
        {
            id: 'google-skillshop',
            name: 'Google Skillshop',
            institution: 'Google',
            description: 'Free training for digital skills and certifications',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'interdisciplinary',
            duration: 'Self-paced',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://skillshop.withgoogle.com/'
        },
        {
            id: 'microsoft-learn',
            name: 'Microsoft Learn',
            institution: 'Microsoft',
            description: 'Free learning paths in cloud, AI, and development',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'Self-paced',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://learn.microsoft.com/'
        },
        {
            id: 'ibm-skillsbuild',
            name: 'IBM SkillsBuild',
            institution: 'IBM',
            description: 'Free training in technology and workplace skills',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'interdisciplinary',
            duration: 'Self-paced',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://skillsbuild.org/'
        },
        {
            id: 'openlearn',
            name: 'OpenLearn',
            institution: 'The Open University',
            description: 'Free online courses in multiple disciplines',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'interdisciplinary',
            duration: 'Self-paced',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://www.open.edu/openlearn/'
        },
        {
            id: 'alison',
            name: 'Alison',
            institution: 'Alison',
            description: 'Free online certification courses',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'interdisciplinary',
            duration: 'Self-paced',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://alison.com/'
        },
        {
            id: 'edraak',
            name: 'Edraak',
            institution: 'Queen Rania Foundation',
            description: 'Free Arabic MOOC platform with STEM courses',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'interdisciplinary',
            duration: 'Varies',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://www.edraak.org/'
        },
        {
            id: 'sololearn',
            name: 'SoloLearn',
            institution: 'SoloLearn',
            description: 'Free mobile-first coding education',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'Self-paced',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://www.sololearn.com/'
        },
        {
            id: 'duolingo',
            name: 'Duolingo',
            institution: 'Duolingo',
            description: 'Free language learning platform',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'humanities',
            duration: 'Self-paced',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://www.duolingo.com/'
        },
        {
            id: 'ted-ed',
            name: 'TED-Ed',
            institution: 'TED',
            description: 'Educational videos and lessons',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'interdisciplinary',
            duration: 'Short videos',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://ed.ted.com/'
        },
        {
            id: 'youtube-edu',
            name: 'Crash Course (YouTube)',
            institution: 'Crash Course',
            description: 'Free educational video series across many subjects',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'interdisciplinary',
            duration: 'Video series',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://www.youtube.com/crashcourse'
        },
        {
            id: 'nasa-stem',
            name: 'NASA STEM Resources',
            institution: 'NASA',
            description: 'Free space science resources and activities',
            type: 'summer',
            cost: 'free',
            location: 'online',
            field: 'stem',
            duration: 'Self-paced',
            eligibility: 'Open to all',
            dates: 'Always available',
            financialAid: 'Free',
            website: 'https://stem.nasa.gov/'
        }
    ]
};