"""
Script to translate all remaining untranslated words in organized_vocabulary.html
from English to Modern Standard Arabic.
"""

import re
from pathlib import Path

# Comprehensive translation dictionary for English vocabulary learning
TRANSLATIONS = {
    # Abstract & Ideas
    "ideal": "مثالي",
    "abstract": "مجرد",
    "concept": "مفهوم",
    "theory": "نظرية",
    "principle": "مبدأ",
    "philosophy": "فلسفة",
    "ideology": "أيديولوجية",
    "notion": "فكرة",
    "hypothesis": "فرضية",
    "assumption": "افتراض",
    
    # Actions & Activities
    "abandon": "يهجر",
    "abolish": "يلغي",
    "absorb": "يمتص",
    "accelerate": "يسرع",
    "accommodate": "يستوعب",
    "accomplish": "ينجز",
    "accumulate": "يتراكم",
    "acquire": "يكتسب",
    "adapt": "يتكيف",
    "adjust": "يعدل",
    "administer": "يدير",
    "admire": "يعجب",
    "adopt": "يتبنى",
    "advance": "يتقدم",
    "advocate": "يؤيد",
    "allocate": "يخصص",
    "alter": "يغير",
    "amend": "يعدل",
    "analyze": "يحلل",
    "anticipate": "يتوقع",
    "appeal": "يناشد",
    "appoint": "يعين",
    "appreciate": "يقدر",
    "approach": "يقترب",
    "approve": "يوافق",
    "argue": "يجادل",
    "arise": "ينشأ",
    "arrange": "يرتب",
    "articulate": "يعبر بوضوح",
    "ascertain": "يتأكد",
    "aspire": "يطمح",
    "assemble": "يجمع",
    "assert": "يؤكد",
    "assess": "يقيّم",
    "assign": "يكلف",
    "assist": "يساعد",
    "associate": "يربط",
    "assume": "يفترض",
    "assure": "يؤكد",
    "attach": "يربط",
    "attain": "يحقق",
    "attempt": "يحاول",
    "attend": "يحضر",
    "attribute": "ينسب",
    "authorize": "يرخص",
    "automate": "يؤتمت",
    
    # Business & Economics
    "accounting": "محاسبة",
    "acquisition": "استحواذ",
    "asset": "أصل",
    "audit": "تدقيق",
    "bankruptcy": "إفلاس",
    "budget": "ميزانية",
    "capital": "رأس مال",
    "commodity": "سلعة",
    "compensation": "تعويض",
    "competition": "منافسة",
    "consumer": "مستهلك",
    "contract": "عقد",
    "corporation": "شركة",
    "credit": "ائتمان",
    "currency": "عملة",
    "debt": "دين",
    "deficit": "عجز",
    "dividend": "توزيعات أرباح",
    "economy": "اقتصاد",
    "efficiency": "كفاءة",
    "employment": "توظيف",
    "enterprise": "مؤسسة",
    "entrepreneur": "رائد أعمال",
    "equity": "ملكية",
    "expenditure": "نفقات",
    "export": "تصدير",
    "finance": "تمويل",
    "fiscal": "مالي",
    "franchise": "امتياز تجاري",
    "gross": "إجمالي",
    "import": "استيراد",
    "income": "دخل",
    "industry": "صناعة",
    "inflation": "تضخم",
    "infrastructure": "بنية تحتية",
    "insurance": "تأمين",
    "interest": "فائدة",
    "inventory": "مخزون",
    "investment": "استثمار",
    "invoice": "فاتورة",
    "labor": "عمل",
    "liability": "التزام",
    "liquidation": "تصفية",
    "loan": "قرض",
    "management": "إدارة",
    "manufacturing": "تصنيع",
    "margin": "هامش",
    "market": "سوق",
    "merchandise": "بضائع",
    "merger": "اندماج",
    "monopoly": "احتكار",
    "mortgage": "رهن عقاري",
    "negotiation": "تفاوض",
    "patent": "براءة اختراع",
    "portfolio": "محفظة",
    "premium": "قسط",
    "procurement": "شراء",
    "productivity": "إنتاجية",
    "profit": "ربح",
    "quota": "حصة",
    "recession": "ركود",
    "refund": "استرداد",
    "regulation": "تنظيم",
    "retail": "تجزئة",
    "revenue": "إيرادات",
    "salary": "راتب",
    "shareholder": "مساهم",
    "stock": "سهم",
    "subsidy": "إعانة",
    "supply": "عرض",
    "surplus": "فائض",
    "tariff": "تعريفة",
    "taxation": "ضرائب",
    "transaction": "معاملة",
    "turnover": "معدل الدوران",
    "venture": "مشروع",
    "wholesale": "جملة",
    
    # Communication & Expression
    "articulation": "تعبير",
    "broadcast": "بث",
    "clarify": "يوضح",
    "communicate": "يتواصل",
    "convey": "ينقل",
    "correspond": "يتراسل",
    "debate": "نقاش",
    "declare": "يعلن",
    "discourse": "خطاب",
    "discuss": "يناقش",
    "elaborate": "يفصّل",
    "emphasize": "يؤكد",
    "express": "يعبر",
    "gesture": "إيماءة",
    "illustrate": "يوضح",
    "imply": "يلمح",
    "inform": "يخبر",
    "interpret": "يفسر",
    "narrate": "يروي",
    "negotiate": "يفاوض",
    "notify": "يخطر",
    "pronounce": "ينطق",
    "publish": "ينشر",
    "recite": "يتلو",
    "remark": "ملاحظة",
    "report": "تقرير",
    "respond": "يرد",
    "rhetoric": "بلاغة",
    "signal": "إشارة",
    "specify": "يحدد",
    "statement": "بيان",
    "transmit": "ينقل",
    "utter": "ينطق",
    "verbalize": "يعبر لفظياً",
    
    # Education & Learning
    "academic": "أكاديمي",
    "curriculum": "منهج دراسي",
    "discipline": "تخصص",
    "dissertation": "أطروحة",
    "doctorate": "دكتوراه",
    "education": "تعليم",
    "enrollment": "تسجيل",
    "examination": "امتحان",
    "faculty": "هيئة تدريس",
    "graduate": "خريج",
    "instruction": "تدريس",
    "knowledge": "معرفة",
    "lecture": "محاضرة",
    "literacy": "محو الأمية",
    "pedagogy": "علم التربية",
    "professor": "أستاذ",
    "qualification": "مؤهل",
    "scholarship": "منحة دراسية",
    "seminar": "ندوة",
    "study": "دراسة",
    "syllabus": "مقرر دراسي",
    "thesis": "رسالة",
    "tuition": "رسوم دراسية",
    "university": "جامعة",
    
    # Emotions & Feelings
    "affection": "عاطفة",
    "agony": "معاناة",
    "amazement": "دهشة",
    "anger": "غضب",
    "anguish": "كرب",
    "anxiety": "قلق",
    "apathy": "لامبالاة",
    "apprehension": "خوف",
    "compassion": "شفقة",
    "contentment": "رضا",
    "delight": "بهجة",
    "despair": "يأس",
    "disappointment": "خيبة أمل",
    "disgust": "اشمئزاز",
    "ecstasy": "نشوة",
    "embarrassment": "إحراج",
    "emotion": "عاطفة",
    "empathy": "تعاطف",
    "enthusiasm": "حماس",
    "envy": "حسد",
    "euphoria": "نشوة",
    "excitement": "إثارة",
    "fear": "خوف",
    "frustration": "إحباط",
    "fury": "غضب شديد",
    "gratitude": "امتنان",
    "grief": "حزن",
    "guilt": "شعور بالذنب",
    "happiness": "سعادة",
    "hatred": "كراهية",
    "hope": "أمل",
    "horror": "رعب",
    "hostility": "عداء",
    "humiliation": "إذلال",
    "irritation": "انزعاج",
    "jealousy": "غيرة",
    "joy": "فرح",
    "loneliness": "وحدة",
    "love": "حب",
    "melancholy": "كآبة",
    "misery": "بؤس",
    "nostalgia": "حنين",
    "optimism": "تفاؤل",
    "panic": "ذعر",
    "passion": "شغف",
    "pessimism": "تشاؤم",
    "pity": "شفقة",
    "pleasure": "سرور",
    "pride": "فخر",
    "rage": "غضب",
    "regret": "ندم",
    "relief": "راحة",
    "resentment": "استياء",
    "sadness": "حزن",
    "satisfaction": "رضا",
    "shame": "خجل",
    "sorrow": "أسى",
    "surprise": "مفاجأة",
    "sympathy": "تعاطف",
    "tension": "توتر",
    "terror": "رعب",
    "wonder": "دهشة",
    "worry": "قلق",
    
    # Environment & Nature
    "atmosphere": "جو",
    "biodiversity": "تنوع بيولوجي",
    "climate": "مناخ",
    "conservation": "حفظ",
    "deforestation": "إزالة الغابات",
    "ecology": "علم البيئة",
    "ecosystem": "نظام بيئي",
    "emission": "انبعاث",
    "endangered": "مهدد بالانقراض",
    "environment": "بيئة",
    "erosion": "تآكل",
    "extinction": "انقراض",
    "fauna": "حيوانات",
    "flora": "نباتات",
    "fossil": "أحفورة",
    "geology": "جيولوجيا",
    "habitat": "موطن",
    "hurricane": "إعصار",
    "landscape": "منظر طبيعي",
    "natural": "طبيعي",
    "organism": "كائن حي",
    "pollution": "تلوث",
    "precipitation": "هطول",
    "preservation": "حفظ",
    "rainforest": "غابة مطيرة",
    "recycling": "إعادة تدوير",
    "renewable": "متجدد",
    "resources": "موارد",
    "species": "أنواع",
    "sustainability": "استدامة",
    "terrain": "تضاريس",
    "vegetation": "نباتات",
    "weather": "طقس",
    "wilderness": "برية",
    "wildlife": "حياة برية",
    
    # Government & Politics
    "administration": "إدارة",
    "amendment": "تعديل",
    "authority": "سلطة",
    "ballot": "اقتراع",
    "bureaucracy": "بيروقراطية",
    "campaign": "حملة",
    "candidate": "مرشح",
    "census": "تعداد سكاني",
    "citizen": "مواطن",
    "coalition": "ائتلاف",
    "congress": "كونغرس",
    "constitution": "دستور",
    "democracy": "ديمقراطية",
    "diplomacy": "دبلوماسية",
    "election": "انتخاب",
    "embassy": "سفارة",
    "federation": "اتحاد",
    "government": "حكومة",
    "governor": "حاكم",
    "legislation": "تشريع",
    "legislature": "هيئة تشريعية",
    "liberty": "حرية",
    "minister": "وزير",
    "ministry": "وزارة",
    "monarchy": "ملكية",
    "parliament": "برلمان",
    "policy": "سياسة",
    "politics": "سياسة",
    "president": "رئيس",
    "referendum": "استفتاء",
    "reform": "إصلاح",
    "regime": "نظام",
    "representative": "ممثل",
    "republic": "جمهورية",
    "senate": "مجلس شيوخ",
    "senator": "سيناتور",
    "sovereignty": "سيادة",
    "state": "دولة",
    "statute": "قانون",
    "treaty": "معاهدة",
    "vote": "تصويت",
    
    # Health & Medicine
    "ailment": "مرض",
    "allergy": "حساسية",
    "anatomy": "تشريح",
    "anesthesia": "تخدير",
    "antibiotic": "مضاد حيوي",
    "arthritis": "التهاب المفاصل",
    "bacteria": "بكتيريا",
    "benign": "حميد",
    "cardiology": "طب القلب",
    "chemotherapy": "علاج كيميائي",
    "chronic": "مزمن",
    "diagnosis": "تشخيص",
    "disease": "مرض",
    "disorder": "اضطراب",
    "epidemic": "وباء",
    "fever": "حمى",
    "fracture": "كسر",
    "genetics": "علم الوراثة",
    "hygiene": "نظافة",
    "immune": "مناعي",
    "infection": "عدوى",
    "inflammation": "التهاب",
    "injury": "إصابة",
    "malignant": "خبيث",
    "medication": "دواء",
    "medicine": "طب",
    "nutrition": "تغذية",
    "obesity": "سمنة",
    "pandemic": "جائحة",
    "pathology": "علم الأمراض",
    "patient": "مريض",
    "pharmacy": "صيدلية",
    "physician": "طبيب",
    "physiology": "علم وظائف الأعضاء",
    "prescription": "وصفة طبية",
    "prevention": "وقاية",
    "prognosis": "تشخيص مسبق",
    "quarantine": "حجر صحي",
    "radiology": "علم الأشعة",
    "rehabilitation": "إعادة تأهيل",
    "remedy": "علاج",
    "sanitation": "صرف صحي",
    "surgery": "جراحة",
    "symptom": "عرض",
    "syndrome": "متلازمة",
    "therapy": "علاج",
    "treatment": "معالجة",
    "vaccination": "تطعيم",
    "vaccine": "لقاح",
    "virus": "فيروس",
    
    # Law & Justice
    "accused": "متهم",
    "acquittal": "براءة",
    "allegation": "ادعاء",
    "appeal": "استئناف",
    "attorney": "محامٍ",
    "bail": "كفالة",
    "charge": "تهمة",
    "civil": "مدني",
    "code": "قانون",
    "conviction": "إدانة",
    "court": "محكمة",
    "crime": "جريمة",
    "criminal": "مجرم",
    "custody": "حجز",
    "defendant": "مدعى عليه",
    "defense": "دفاع",
    "evidence": "دليل",
    "felony": "جناية",
    "fraud": "احتيال",
    "guilty": "مذنب",
    "illegal": "غير قانوني",
    "indictment": "لائحة اتهام",
    "innocent": "بريء",
    "judge": "قاضي",
    "jurisdiction": "ولاية قضائية",
    "jury": "هيئة محلفين",
    "justice": "عدالة",
    "lawsuit": "دعوى قضائية",
    "lawyer": "محامٍ",
    "legal": "قانوني",
    "legislation": "تشريع",
    "liability": "مسؤولية",
    "litigation": "تقاضي",
    "misdemeanor": "جنحة",
    "offense": "مخالفة",
    "parole": "إفراج مشروط",
    "penalty": "عقوبة",
    "plaintiff": "مدعي",
    "plea": "طلب",
    "precedent": "سابقة",
    "prison": "سجن",
    "probation": "مراقبة",
    "prosecution": "ادعاء",
    "punishment": "عقاب",
    "sentence": "حكم",
    "statute": "قانون",
    "sued": "مقاضى",
    "testimony": "شهادة",
    "theft": "سرقة",
    "trial": "محاكمة",
    "verdict": "حكم",
    "violation": "انتهاك",
    "warrant": "مذكرة",
    "witness": "شاهد",
    
    # Science & Technology
    "algorithm": "خوارزمية",
    "analysis": "تحليل",
    "apparatus": "جهاز",
    "application": "تطبيق",
    "artificial": "اصطناعي",
    "astronomy": "علم الفلك",
    "atom": "ذرة",
    "biology": "علم الأحياء",
    "chemistry": "كيمياء",
    "circuit": "دائرة",
    "clone": "استنساخ",
    "compound": "مركب",
    "computation": "حساب",
    "computer": "حاسوب",
    "data": "بيانات",
    "database": "قاعدة بيانات",
    "digital": "رقمي",
    "electricity": "كهرباء",
    "electron": "إلكترون",
    "element": "عنصر",
    "energy": "طاقة",
    "engineering": "هندسة",
    "equation": "معادلة",
    "evolution": "تطور",
    "experiment": "تجربة",
    "formula": "صيغة",
    "frequency": "تردد",
    "function": "دالة",
    "genetics": "علم الوراثة",
    "geometry": "هندسة",
    "gravity": "جاذبية",
    "hardware": "عتاد",
    "hypothesis": "فرضية",
    "innovation": "ابتكار",
    "internet": "إنترنت",
    "invention": "اختراع",
    "laboratory": "مختبر",
    "laser": "ليزر",
    "mathematics": "رياضيات",
    "matter": "مادة",
    "measurement": "قياس",
    "mechanics": "ميكانيكا",
    "methodology": "منهجية",
    "microscope": "مجهر",
    "molecule": "جزيء",
    "network": "شبكة",
    "nuclear": "نووي",
    "observation": "ملاحظة",
    "particle": "جسيم",
    "phenomenon": "ظاهرة",
    "physics": "فيزياء",
    "processor": "معالج",
    "programming": "برمجة",
    "quantum": "كمومي",
    "radiation": "إشعاع",
    "reaction": "تفاعل",
    "research": "بحث",
    "robot": "روبوت",
    "satellite": "قمر صناعي",
    "scientific": "علمي",
    "simulation": "محاكاة",
    "software": "برمجيات",
    "solar": "شمسي",
    "solution": "محلول",
    "spectrum": "طيف",
    "statistics": "إحصاء",
    "substance": "مادة",
    "system": "نظام",
    "technology": "تكنولوجيا",
    "telecommunications": "اتصالات",
    "telescope": "تلسكوب",
    "temperature": "درجة حرارة",
    "theory": "نظرية",
    "tissue": "نسيج",
    "variable": "متغير",
    "velocity": "سرعة",
    "voltage": "جهد كهربائي",
    "wavelength": "طول موجي",
    
    # Social & Cultural
    "ancestry": "نسب",
    "anthropology": "علم الإنسان",
    "artifact": "قطعة أثرية",
    "beliefs": "معتقدات",
    "ceremony": "حفل",
    "civilization": "حضارة",
    "class": "طبقة",
    "community": "مجتمع",
    "convention": "اتفاقية",
    "culture": "ثقافة",
    "custom": "عرف",
    "dialect": "لهجة",
    "discrimination": "تمييز",
    "diversity": "تنوع",
    "equality": "مساواة",
    "ethnicity": "عرق",
    "festival": "مهرجان",
    "folklore": "فلكلور",
    "generation": "جيل",
    "heritage": "تراث",
    "hierarchy": "تسلسل هرمي",
    "identity": "هوية",
    "inequality": "عدم مساواة",
    "kinship": "قرابة",
    "language": "لغة",
    "legacy": "إرث",
    "legend": "أسطورة",
    "lifestyle": "أسلوب حياة",
    "marriage": "زواج",
    "migration": "هجرة",
    "minority": "أقلية",
    "morality": "أخلاق",
    "myth": "أسطورة",
    "nationality": "جنسية",
    "norm": "معيار",
    "origin": "أصل",
    "population": "سكان",
    "poverty": "فقر",
    "prejudice": "تحيز",
    "privilege": "امتياز",
    "race": "عرق",
    "religion": "دين",
    "ritual": "طقوس",
    "rural": "ريفي",
    "sect": "طائفة",
    "segregation": "فصل عنصري",
    "social": "اجتماعي",
    "society": "مجتمع",
    "sociology": "علم الاجتماع",
    "status": "حالة",
    "stereotype": "صورة نمطية",
    "stratification": "تطبق",
    "symbol": "رمز",
    "taboo": "محرم",
    "tradition": "تقليد",
    "tribe": "قبيلة",
    "unemployment": "بطالة",
    "urban": "حضري",
    "values": "قيم",
    "wealth": "ثروة",
    "welfare": "رفاهية",
    
    # Transportation & Travel
    "acceleration": "تسارع",
    "aircraft": "طائرة",
    "airport": "مطار",
    "automobile": "سيارة",
    "aviation": "طيران",
    "cargo": "شحن",
    "carrier": "ناقل",
    "commute": "تنقل",
    "departure": "مغادرة",
    "destination": "وجهة",
    "excursion": "رحلة",
    "expedition": "بعثة",
    "fare": "أجرة",
    "ferry": "عبارة",
    "freight": "بضائع",
    "highway": "طريق سريع",
    "itinerary": "خط سير",
    "journey": "رحلة",
    "luggage": "أمتعة",
    "navigation": "ملاحة",
    "passenger": "راكب",
    "pilot": "طيار",
    "railway": "سكة حديد",
    "route": "طريق",
    "shipment": "شحنة",
    "terminal": "محطة",
    "ticket": "تذكرة",
    "tourism": "سياحة",
    "traffic": "حركة المرور",
    "transit": "عبور",
    "transportation": "نقل",
    "travel": "سفر",
    "vehicle": "مركبة",
    "vessel": "سفينة",
    "voyage": "رحلة بحرية",
    
    # Time & Space
    "ancient": "قديم",
    "annual": "سنوي",
    "antique": "عتيق",
    "calendar": "تقويم",
    "century": "قرن",
    "chronological": "زمني",
    "contemporary": "معاصر",
    "continual": "مستمر",
    "decade": "عقد",
    "delay": "تأخير",
    "duration": "مدة",
    "epoch": "عصر",
    "era": "حقبة",
    "eternal": "أبدي",
    "everlasting": "خالد",
    "frequent": "متكرر",
    "future": "مستقبل",
    "historical": "تاريخي",
    "history": "تاريخ",
    "immediate": "فوري",
    "instant": "لحظة",
    "interval": "فترة",
    "medieval": "قروسطي",
    "millennium": "ألفية",
    "modern": "حديث",
    "moment": "لحظة",
    "monthly": "شهري",
    "occasion": "مناسبة",
    "period": "فترة",
    "permanent": "دائم",
    "prehistoric": "ما قبل التاريخ",
    "present": "حاضر",
    "prior": "سابق",
    "punctual": "دقيق",
    "recent": "حديث",
    "schedule": "جدول",
    "seasonal": "موسمي",
    "simultaneous": "متزامن",
    "subsequent": "لاحق",
    "temporary": "مؤقت",
    "timeless": "خالد",
    "vintage": "قديم",
    "weekly": "أسبوعي",
    
    # Additional common words
    "abandon": "يهجر",
    "abide": "يلتزم",
    "abolish": "يلغي",
    "abundant": "وفير",
    "accurate": "دقيق",
    "achieve": "يحقق",
    "acknowledge": "يقر",
    "adequate": "كافٍ",
    "adjacent": "مجاور",
    "admirable": "جدير بالإعجاب",
    "adverse": "معاكس",
    "aesthetic": "جمالي",
    "affirmative": "إيجابي",
    "aggressive": "عدواني",
    "agile": "رشيق",
    "agreeable": "مقبول",
    "alert": "يقظ",
    "alienate": "يبعد",
    "alleviate": "يخفف",
    "alternate": "يتناوب",
    "amateur": "هاوٍ",
    "ambiguous": "غامض",
    "ambitious": "طموح",
    "ample": "واسع",
    "analogous": "مماثل",
    "ancient": "قديم",
    "anonymous": "مجهول",
    "antagonist": "خصم",
    "antique": "عتيق",
    "anxious": "قلق",
    "apparent": "واضح",
    "applicable": "قابل للتطبيق",
    "appraise": "يقيّم",
    "arbitrary": "تعسفي",
    "arduous": "شاق",
    "arrogant": "متكبر",
    "articulate": "فصيح",
    "artificial": "اصطناعي",
    "ascend": "يصعد",
    "aspiring": "طموح",
    "assiduous": "مجتهد",
    "astonish": "يدهش",
    "astute": "فطن",
    "attentive": "منتبه",
    "audacious": "جريء",
    "authentic": "أصيل",
    "authoritative": "موثوق",
    "autonomous": "مستقل",
    "averse": "نافر",
    "awkward": "محرج",
    
    # More B words
    "baffle": "يحير",
    "barren": "قاحل",
    "benevolent": "خير",
    "biased": "متحيز",
    "bizarre": "غريب",
    "bland": "لطيف",
    "bleak": "كئيب",
    "blunt": "صريح",
    "boisterous": "صاخب",
    "bold": "جريء",
    "brisk": "نشيط",
    "brittle": "هش",
    "brutal": "وحشي",
    "buoyant": "طافي",
    
    # C words
    "callous": "قاسي",
    "candid": "صريح",
    "capable": "قادر",
    "captivate": "يسحر",
    "cautious": "حذر",
    "cease": "يتوقف",
    "celestial": "سماوي",
    "certain": "مؤكد",
    "chaotic": "فوضوي",
    "characteristic": "مميز",
    "charitable": "خيري",
    "cherish": "يعتز",
    "chivalrous": "نبيل",
    "chronic": "مزمن",
    "circumstances": "ظروف",
    "civic": "مدني",
    "clamor": "ضجيج",
    "clarification": "توضيح",
    "classify": "يصنف",
    "clemency": "رحمة",
    "cognitive": "معرفي",
    "coherent": "متماسك",
    "coincide": "يتزامن",
    "collapse": "ينهار",
    "collective": "جماعي",
    "collide": "يصطدم",
    "colossal": "ضخم",
    "commence": "يبدأ",
    "compatible": "متوافق",
    "compelling": "مقنع",
    "competent": "كفء",
    "compile": "يجمع",
    "complacent": "راضٍ عن النفس",
    "complement": "يكمل",
    "complex": "معقد",
    "compliant": "ممتثل",
    "comprehensive": "شامل",
    "compromise": "تسوية",
    "compulsory": "إلزامي",
    "conceal": "يخفي",
    "concede": "يعترف",
    "conceive": "يتصور",
    "concentrate": "يركز",
    "concise": "موجز",
    "conclude": "يستنتج",
    "concrete": "خرساني",
    "condemn": "يدين",
    "condense": "يكثف",
    "conducive": "مواتٍ",
    "conduct": "يدير",
    "confident": "واثق",
    "confine": "يحصر",
    "confirm": "يؤكد",
    "conflict": "صراع",
    "conform": "يتوافق",
    "confront": "يواجه",
    "confuse": "يربك",
    "congestion": "ازدحام",
    "conjecture": "تخمين",
    "conscientious": "ضميري",
    "conscious": "واعٍ",
    "consecutive": "متتالي",
    "consensus": "إجماع",
    "consequence": "نتيجة",
    "conservative": "محافظ",
    "considerable": "كبير",
    "considerate": "مراعٍ",
    "consistent": "متسق",
    "consolidate": "يوحد",
    "conspicuous": "واضح",
    "constant": "ثابت",
    "constitute": "يشكل",
    "constrain": "يقيد",
    "construct": "يبني",
    "consult": "يستشير",
    "consume": "يستهلك",
    "contagious": "معدي",
    "contain": "يحتوي",
    "contaminate": "يلوث",
    "contemplate": "يتأمل",
    "contempt": "احتقار",
    "contend": "يناضل",
    "content": "راضٍ",
    "contest": "منافسة",
    "context": "سياق",
    "contingent": "مشروط",
    "continuous": "مستمر",
    "contradict": "يناقض",
    "contrary": "مخالف",
    "contrast": "تباين",
    "contribute": "يساهم",
    "controversial": "مثير للجدل",
    "convenient": "مريح",
    "conventional": "تقليدي",
    "converge": "يتقارب",
    "conversant": "ملم",
    "converse": "يحادث",
    "conversion": "تحويل",
    "convert": "يحول",
    "convict": "يدين",
    "convince": "يقنع",
    "coordinate": "ينسق",
    "cope": "يتعامل",
    "cordial": "ودي",
    "corporate": "مؤسسي",
    "correlate": "يربط",
    "correspond": "يتوافق",
    "corroborate": "يؤكد",
    "corrupt": "فاسد",
    "cosmopolitan": "عالمي",
    "counsel": "نصيحة",
    "counteract": "يعاكس",
    "countless": "لا يحصى",
    "courteous": "مهذب",
    "covert": "خفي",
    "covetous": "طماع",
    "credible": "موثوق",
    "critical": "حرج",
    "critique": "نقد",
    "crucial": "حاسم",
    "crude": "خام",
    "cruel": "قاسٍ",
    "cultivate": "يزرع",
    "cumbersome": "مرهق",
    "cumulative": "تراكمي",
    "cunning": "ماكر",
    "curb": "يكبح",
    "curious": "فضولي",
    "current": "حالي",
    "cursory": "سريع",
    "curtail": "يقلص",
    "cynical": "ساخر",
    
    # D words
    "daunting": "مخيف",
    "dazzle": "يبهر",
    "deceive": "يخدع",
    "decent": "لائق",
    "decisive": "حاسم",
    "decline": "يرفض",
    "dedicate": "يكرس",
    "deduce": "يستنتج",
    "deem": "يعتبر",
    "defect": "عيب",
    "deficient": "ناقص",
    "define": "يحدد",
    "definite": "محدد",
    "deflect": "يصد",
    "defy": "يتحدى",
    "degradation": "تدهور",
    "deliberate": "متعمد",
    "delicate": "رقيق",
    "delinquent": "مقصر",
    "deliver": "يسلم",
    "delusion": "وهم",
    "demanding": "مطالب",
    "demolish": "يهدم",
    "demonstrate": "يظهر",
    "dense": "كثيف",
    "depict": "يصور",
    "deplete": "يستنزف",
    "deploy": "ينشر",
    "depreciate": "ينخفض",
    "deprive": "يحرم",
    "derive": "يستمد",
    "descend": "يهبط",
    "designate": "يسمي",
    "desirable": "مرغوب",
    "desolate": "موحش",
    "desperate": "يائس",
    "despise": "يحتقر",
    "destined": "مقدر",
    "destitute": "معدم",
    "destroy": "يدمر",
    "detach": "يفصل",
    "detail": "تفصيل",
    "detain": "يحتجز",
    "detect": "يكتشف",
    "deter": "يردع",
    "deteriorate": "يتدهور",
    "determine": "يحدد",
    "detest": "يكره",
    "detrimental": "ضار",
    "devastate": "يدمر",
    "deviate": "ينحرف",
    "devise": "يبتكر",
    "devote": "يكرس",
    "dexterous": "ماهر",
    "diagnose": "يشخص",
    "diligent": "مجتهد",
    "dilute": "يخفف",
    "diminish": "يقلل",
    "dire": "رهيب",
    "disable": "يعطل",
    "disadvantage": "عيب",
    "discard": "يتخلص",
    "discern": "يميز",
    "discharge": "يطلق",
    "disclose": "يكشف",
    "discomfort": "عدم راحة",
    "disconnect": "يفصل",
    "discreet": "حذر",
    "discretion": "تقدير",
    "discriminate": "يميز",
    "disdain": "ازدراء",
    "dismantle": "يفكك",
    "dismiss": "يرفض",
    "disorder": "فوضى",
    "disparate": "مختلف",
    "dispatch": "يرسل",
    "dispel": "يبدد",
    "disperse": "يشتت",
    "displace": "يزيح",
    "display": "يعرض",
    "dispose": "يتخلص",
    "dispute": "نزاع",
    "disregard": "يتجاهل",
    "disrupt": "يعطل",
    "dissent": "اختلاف",
    "dissolve": "يذوب",
    "dissuade": "يثني",
    "distant": "بعيد",
    "distinct": "متميز",
    "distinguish": "يميز",
    "distort": "يشوه",
    "distract": "يشتت",
    "distress": "ضيق",
    "distribute": "يوزع",
    "distrust": "عدم ثقة",
    "disturb": "يزعج",
    "diverse": "متنوع",
    "divert": "يحول",
    "divide": "يقسم",
    "divine": "إلهي",
    "divulge": "يفشي",
    "docile": "مطيع",
    "doctrine": "مذهب",
    "document": "وثيقة",
    "dogmatic": "متعصب",
    "domain": "مجال",
    "domestic": "منزلي",
    "dominant": "مهيمن",
    "dominate": "يهيمن",
    "donate": "يتبرع",
    "dormant": "خامل",
    "doubtful": "مشكوك",
    "drastic": "جذري",
    "dread": "رهبة",
    "dubious": "مشكوك",
    "dull": "ممل",
    "duplicate": "نسخة",
    "durable": "متين",
    "dwindle": "يتضاءل",
    "dynamic": "ديناميكي",
    
    # E words
    "eager": "متلهف",
    "earnest": "جاد",
    "eccentric": "شاذ",
    "eclipse": "كسوف",
    "ecological": "بيئي",
    "economical": "اقتصادي",
    "edible": "صالح للأكل",
    "editorial": "افتتاحية",
    "effective": "فعال",
    "efficient": "كفء",
    "elaborate": "مفصل",
    "elastic": "مرن",
    "elated": "مبتهج",
    "elderly": "مسن",
    "elect": "ينتخب",
    "elegant": "أنيق",
    "elementary": "أساسي",
    "elevate": "يرفع",
    "eligible": "مؤهل",
    "eliminate": "يزيل",
    "elite": "نخبة",
    "eloquent": "فصيح",
    "elude": "يتهرب",
    "emancipate": "يحرر",
    "embark": "يبدأ",
    "embarrass": "يحرج",
    "embed": "يضمن",
    "embellish": "يزين",
    "embrace": "يحتضن",
    "emerge": "يظهر",
    "emergency": "طوارئ",
    "emigrate": "يهاجر",
    "eminent": "بارز",
    "emit": "يطلق",
    "emphasize": "يؤكد",
    "empirical": "تجريبي",
    "employ": "يوظف",
    "empower": "يمكن",
    "enact": "يسن",
    "encounter": "يواجه",
    "encourage": "يشجع",
    "endeavor": "مسعى",
    "endorse": "يؤيد",
    "endow": "يمنح",
    "endure": "يتحمل",
    "enforce": "ينفذ",
    "engage": "ينخرط",
    "enhance": "يعزز",
    "enigma": "لغز",
    "enlighten": "ينير",
    "enormous": "هائل",
    "enrich": "يثري",
    "ensure": "يضمن",
    "entail": "يستلزم",
    "enterprise": "مشروع",
    "entertain": "يسلي",
    "enthusiasm": "حماس",
    "entice": "يغري",
    "entire": "كامل",
    "entitle": "يخول",
    "entity": "كيان",
    "enumerate": "يعدد",
    "envious": "حسود",
    "episode": "حلقة",
    "equitable": "عادل",
    "equivalent": "مكافئ",
    "era": "عصر",
    "eradicate": "يستأصل",
    "erect": "ينصب",
    "erode": "يتآكل",
    "erratic": "متقلب",
    "error": "خطأ",
    "erudite": "عالم",
    "escalate": "يتصاعد",
    "escape": "يهرب",
    "essential": "أساسي",
    "establish": "يؤسس",
    "esteem": "احترام",
    "estimate": "يقدر",
    "eternal": "أبدي",
    "ethical": "أخلاقي",
    "ethnic": "عرقي",
    "evacuate": "يخلي",
    "evade": "يتهرب",
    "evaluate": "يقيّم",
    "evaporate": "يتبخر",
    "eventually": "في النهاية",
    "evident": "واضح",
    "evoke": "يستحضر",
    "evolve": "يتطور",
    "exacerbate": "يفاقم",
    "exact": "دقيق",
    "exaggerate": "يبالغ",
    "exalt": "يعلي",
    "examine": "يفحص",
    "exceed": "يتجاوز",
    "excel": "يتفوق",
    "exceptional": "استثنائي",
    "excerpt": "مقتطف",
    "excess": "فائض",
    "exchange": "تبادل",
    "excite": "يثير",
    "exclude": "يستثني",
    "exclusive": "حصري",
    "execute": "ينفذ",
    "exemplary": "مثالي",
    "exempt": "معفي",
    "exercise": "تمرين",
    "exert": "يبذل",
    "exhaust": "يستنزف",
    "exhibit": "يعرض",
    "exhilarate": "يبهج",
    "exile": "منفى",
    "existence": "وجود",
    "expand": "يوسع",
    "expectation": "توقع",
    "expedite": "يعجل",
    "expel": "يطرد",
    "expenditure": "نفقات",
    "expertise": "خبرة",
    "expire": "ينتهي",
    "explicit": "صريح",
    "exploit": "يستغل",
    "explore": "يستكشف",
    "expose": "يكشف",
    "expression": "تعبير",
    "expulsion": "طرد",
    "exquisite": "رائع",
    "extend": "يمتد",
    "extensive": "واسع",
    "extent": "مدى",
    "exterior": "خارجي",
    "external": "خارجي",
    "extinct": "منقرض",
    "extinguish": "يطفئ",
    "extol": "يمدح",
    "extract": "يستخلص",
    "extraordinary": "استثنائي",
    "extravagant": "مسرف",
    "extreme": "متطرف",
    "exuberant": "منتشٍ",
    
    # F words
    "fabricate": "يصنع",
    "fabulous": "رائع",
    "facilitate": "ييسر",
    "faction": "فصيل",
    "faculty": "ملكة",
    "faint": "خافت",
    "faithful": "مخلص",
    "fallacy": "مغالطة",
    "fame": "شهرة",
    "familiar": "مألوف",
    "famine": "مجاعة",
    "fanatic": "متعصب",
    "fancy": "فاخر",
    "fantastic": "خيالي",
    "fascinate": "يفتن",
    "fatal": "قاتل",
    "fatigue": "إرهاق",
    "fault": "خطأ",
    "favorable": "مواتٍ",
    "feasible": "ممكن",
    "feat": "إنجاز",
    "feature": "ميزة",
    "feeble": "ضعيف",
    "fertile": "خصب",
    "fervent": "حار",
    "fierce": "شرس",
    "figure": "شكل",
    "final": "نهائي",
    "finance": "يمول",
    "finite": "محدود",
    "firm": "صلب",
    "flexible": "مرن",
    "flourish": "يزدهر",
    "fluctuate": "يتقلب",
    "fluent": "طليق",
    "focus": "تركيز",
    "foil": "يحبط",
    "forbid": "يحظر",
    "force": "قوة",
    "forecast": "توقع",
    "foreign": "أجنبي",
    "foresee": "يتوقع",
    "forge": "يشكل",
    "formal": "رسمي",
    "formidable": "هائل",
    "formula": "صيغة",
    "formulate": "يصيغ",
    "forsake": "يتخلى",
    "forthcoming": "قادم",
    "fortune": "ثروة",
    "foster": "يرعى",
    "foundation": "أساس",
    "fracture": "كسر",
    "fragile": "هش",
    "fragment": "شظية",
    "framework": "إطار",
    "frank": "صريح",
    "fraud": "احتيال",
    "frequent": "متكرر",
    "friction": "احتكاك",
    "frigid": "بارد جداً",
    "frugal": "مقتصد",
    "frustrate": "يحبط",
    "fulfill": "يحقق",
    "fundamental": "أساسي",
    "furnish": "يوفر",
    "futile": "عقيم",
    
    # G words
    "gain": "يكسب",
    "gallant": "شجاع",
    "gap": "فجوة",
    "gather": "يجمع",
    "gauge": "مقياس",
    "general": "عام",
    "generate": "يولد",
    "generous": "كريم",
    "genius": "عبقري",
    "genre": "نوع",
    "genuine": "حقيقي",
    "gesture": "إيماءة",
    "gigantic": "عملاق",
    "glamorous": "ساحر",
    "glance": "لمحة",
    "gloomy": "كئيب",
    "glory": "مجد",
    "govern": "يحكم",
    "grace": "نعمة",
    "gradual": "تدريجي",
    "grand": "فخم",
    "grant": "منحة",
    "grasp": "يفهم",
    "grateful": "ممتن",
    "gratify": "يرضي",
    "grave": "خطير",
    "greed": "طمع",
    "grieve": "يحزن",
    "grim": "قاتم",
    "gross": "فظ",
    "guarantee": "ضمان",
    "guard": "حارس",
    "guidance": "توجيه",
    "guild": "نقابة",
    "guilty": "مذنب",
    
    # H words
    "habitual": "معتاد",
    "halt": "يوقف",
    "hamper": "يعيق",
    "handsome": "وسيم",
    "haphazard": "عشوائي",
    "harass": "يضايق",
    "harbor": "ميناء",
    "hardship": "مشقة",
    "hardy": "قوي",
    "harm": "ضرر",
    "harmonious": "متناغم",
    "harsh": "قاسٍ",
    "hasten": "يعجل",
    "hasty": "متسرع",
    "haughty": "متكبر",
    "hazard": "خطر",
    "heal": "يشفي",
    "heap": "كومة",
    "heartfelt": "صادق",
    "hectic": "محموم",
    "heed": "يصغي",
    "heighten": "يزيد",
    "heir": "وريث",
    "hence": "من ثم",
    "herald": "ينذر",
    "hereditary": "وراثي",
    "heritage": "تراث",
    "hermit": "ناسك",
    "hesitate": "يتردد",
    "hierarchy": "تسلسل هرمي",
    "highlight": "يبرز",
    "hinder": "يعيق",
    "hint": "تلميح",
    "hoard": "يكتنز",
    "hollow": "أجوف",
    "homage": "تكريم",
    "homogeneous": "متجانس",
    "honest": "أمين",
    "honor": "شرف",
    "hostile": "عدائي",
    "humble": "متواضع",
    "humiliate": "يذل",
    "hypothesis": "فرضية",
    
    # I words (continued)
    "identical": "مطابق",
    "identify": "يحدد",
    "idle": "خامل",
    "ignorant": "جاهل",
    "ignore": "يتجاهل",
    "illustrate": "يوضح",
    "illustrious": "مرموق",
    "image": "صورة",
    "imaginary": "خيالي",
    "imagine": "يتخيل",
    "imitate": "يقلد",
    "immature": "غير ناضج",
    "immense": "هائل",
    "immerse": "يغمر",
    "immigrate": "يهاجر",
    "imminent": "وشيك",
    "immortal": "خالد",
    "immune": "محصن",
    "impact": "تأثير",
    "impair": "يضعف",
    "impart": "يمنح",
    "impartial": "محايد",
    "impede": "يعيق",
    "impel": "يدفع",
    "imperative": "أمر",
    "imperfect": "ناقص",
    "imperial": "إمبراطوري",
    "implement": "ينفذ",
    "implicate": "يورط",
    "implicit": "ضمني",
    "implore": "يتوسل",
    "imply": "يلمح",
    "import": "يستورد",
    "impose": "يفرض",
    "impress": "يثير الإعجاب",
    "impressive": "مثير للإعجاب",
    "imprison": "يسجن",
    "improper": "غير لائق",
    "improve": "يحسن",
    "impulse": "دافع",
    "inability": "عجز",
    "inadequate": "غير كافٍ",
    "incentive": "حافز",
    "incessant": "مستمر",
    "incident": "حادث",
    "incline": "يميل",
    "include": "يشمل",
    "incompatible": "غير متوافق",
    "incomplete": "غير مكتمل",
    "inconsistent": "غير متسق",
    "incorporate": "يدمج",
    "increase": "يزيد",
    "incredible": "لا يصدق",
    "incur": "يتكبد",
    "indebted": "مدين",
    "indeed": "حقاً",
    "indefinite": "غير محدد",
    "independence": "استقلال",
    "indicate": "يشير",
    "indifferent": "غير مبالٍ",
    "indigenous": "محلي",
    "indignant": "غاضب",
    "indirect": "غير مباشر",
    "indispensable": "لا غنى عنه",
    "individual": "فرد",
    "induce": "يحث",
    "indulge": "يدلل",
    "industrial": "صناعي",
    "ineffective": "غير فعال",
    "inevitable": "حتمي",
    "inexorable": "لا يرحم",
    "infamous": "سيئ السمعة",
    "infant": "رضيع",
    "infer": "يستنتج",
    "inferior": "أدنى",
    "infinite": "لا نهائي",
    "inflict": "يلحق",
    "influence": "تأثير",
    "influential": "مؤثر",
    "inform": "يخبر",
    "informal": "غير رسمي",
    "ingenious": "ذكي",
    "inherent": "متأصل",
    "inherit": "يرث",
    "inhibit": "يكبح",
    "initial": "أولي",
    "initiate": "يبدأ",
    "initiative": "مبادرة",
    "injure": "يصيب",
    "injustice": "ظلم",
    "innate": "فطري",
    "inner": "داخلي",
    "innocent": "بريء",
    "innovate": "يبتكر",
    "innumerable": "لا يحصى",
    "inquire": "يستفسر",
    "inquisitive": "فضولي",
    "insane": "مجنون",
    "inscribe": "ينقش",
    "insect": "حشرة",
    "insecure": "غير آمن",
    "insert": "يدرج",
    "insight": "بصيرة",
    "insignificant": "تافه",
    "insincere": "غير صادق",
    "insist": "يصر",
    "insolent": "وقح",
    "inspect": "يفتش",
    "inspire": "يلهم",
    "install": "يركب",
    "instance": "مثال",
    "instant": "فوري",
    "instead": "بدلاً من ذلك",
    "instinct": "غريزة",
    "institute": "معهد",
    "instruct": "يعلّم",
    "instrument": "أداة",
    "insufficient": "غير كافٍ",
    "insult": "إهانة",
    "intact": "سليم",
    "integral": "متكامل",
    "integrate": "يدمج",
    "integrity": "نزاهة",
    "intellect": "ذكاء",
    "intelligent": "ذكي",
    "intend": "ينوي",
    "intense": "شديد",
    "intent": "نية",
    "interact": "يتفاعل",
    "intercept": "يعترض",
    "interfere": "يتدخل",
    "interior": "داخلي",
    "intermediate": "متوسط",
    "internal": "داخلي",
    "international": "دولي",
    "interpret": "يفسر",
    "interrupt": "يقاطع",
    "interval": "فترة",
    "intervene": "يتدخل",
    "intimate": "حميم",
    "intimidate": "يخيف",
    "intricate": "معقد",
    "intrigue": "يثير الفضول",
    "intrinsic": "جوهري",
    "introduce": "يقدم",
    "intrude": "يتطفل",
    "intuition": "حدس",
    "invade": "يغزو",
    "invalid": "باطل",
    "invaluable": "لا يقدر بثمن",
    "invariable": "ثابت",
    "invasion": "غزو",
    "invent": "يخترع",
    "investigate": "يحقق",
    "invigorate": "ينشط",
    "invincible": "لا يقهر",
    "invisible": "غير مرئي",
    "invite": "يدعو",
    "invoke": "يستدعي",
    "involve": "يشمل",
    "inward": "داخلي",
    "irrational": "غير عقلاني",
    "irregular": "غير منتظم",
    "irrelevant": "غير ذي صلة",
    "irresistible": "لا يقاوم",
    "irresponsible": "غير مسؤول",
    "irreversible": "لا رجعة فيه",
    "irrigate": "يروي",
    "irritable": "سريع الانفعال",
    "isolate": "يعزل",
    "issue": "قضية",
    
    # J words
    "jargon": "مصطلحات",
    "jealous": "غيور",
    "jeopardize": "يعرض للخطر",
    "jest": "مزاح",
    "jolt": "هزة",
    "jovial": "مرح",
    "jubilant": "مبتهج",
    "judge": "يحكم",
    "judgment": "حكم",
    "judicial": "قضائي",
    "judicious": "حكيم",
    "junction": "تقاطع",
    "junior": "أصغر",
    "just": "عادل",
    "justify": "يبرر",
    "juvenile": "حدث",
    
    # K words
    "keen": "حريص",
    "kernel": "نواة",
    "keynote": "كلمة افتتاحية",
    "kindle": "يشعل",
    "kindred": "قرابة",
    "knack": "موهبة",
    "knit": "يحيك",
    "knowledge": "معرفة",
    "knowledgeable": "عليم",
    
    # L words
    "labor": "عمل",
    "laborious": "شاق",
    "lack": "نقص",
    "lag": "تأخر",
    "lament": "ينوح",
    "landmark": "معلم",
    "lapse": "هفوة",
    "latent": "كامن",
    "lateral": "جانبي",
    "latter": "الأخير",
    "laudable": "جدير بالثناء",
    "launch": "يطلق",
    "lavish": "سخي",
    "lawful": "قانوني",
    "lax": "متراخٍ",
    "layer": "طبقة",
    "lazy": "كسول",
    "lead": "يقود",
    "league": "دوري",
    "lean": "يميل",
    "leap": "قفزة",
    "learned": "متعلم",
    "lease": "إيجار",
    "leave": "يغادر",
    "lecture": "محاضرة",
    "ledge": "حافة",
    "legacy": "إرث",
    "legal": "قانوني",
    "legend": "أسطورة",
    "legislation": "تشريع",
    "legitimate": "شرعي",
    "leisure": "فراغ",
    "lenient": "متساهل",
    "lessen": "يقلل",
    "lethal": "قاتل",
    "lethargic": "خامل",
    "level": "مستوى",
    "leverage": "نفوذ",
    "levy": "يفرض",
    "liable": "مسؤول",
    "liberal": "ليبرالي",
    "liberate": "يحرر",
    "liberty": "حرية",
    "license": "رخصة",
    "lied": "كذب",
    "lift": "يرفع",
    "light": "خفيف",
    "likewise": "بالمثل",
    "limb": "طرف",
    "limit": "حد",
    "linear": "خطي",
    "linger": "يتباطأ",
    "linguistic": "لغوي",
    "link": "رابط",
    "liquid": "سائل",
    "list": "قائمة",
    "literal": "حرفي",
    "literary": "أدبي",
    "literate": "متعلم",
    "literature": "أدب",
    "litigate": "يتقاضى",
    "litter": "قمامة",
    "lively": "حيوي",
    "load": "حمولة",
    "loan": "قرض",
    "lobby": "يضغط",
    "local": "محلي",
    "locate": "يحدد موقع",
    "location": "موقع",
    "lodge": "نزل",
    "lofty": "سامٍ",
    "logic": "منطق",
    "logical": "منطقي",
    "lone": "وحيد",
    "longevity": "طول عمر",
    "longing": "شوق",
    "loose": "فضفاض",
    "loot": "ينهب",
    "lore": "معرفة",
    "lose": "يفقد",
    "loss": "خسارة",
    "lot": "قطعة",
    "loud": "عالٍ",
    "lounge": "صالة",
    "loyal": "مخلص",
    "lucid": "واضح",
    "lucky": "محظوظ",
    "lucrative": "مربح",
    "ludicrous": "سخيف",
    "luggage": "أمتعة",
    "lukewarm": "فاتر",
    "lull": "هدوء",
    "luminous": "مضيء",
    "lump": "كتلة",
    "lunar": "قمري",
    "lunch": "غداء",
    "lure": "يغري",
    "lurk": "يختبئ",
    "lush": "خصب",
    "luster": "بريق",
    "luxury": "رفاهية",
    
    # M words (continued)
    "machine": "آلة",
    "mad": "مجنون",
    "magazine": "مجلة",
    "magic": "سحر",
    "magistrate": "قاضٍ",
    "magnanimous": "كريم",
    "magnate": "قطب",
    "magnetic": "مغناطيسي",
    "magnificent": "رائع",
    "magnify": "يكبر",
    "magnitude": "قدر",
    "maiden": "عذراء",
    "mail": "بريد",
    "maim": "يشوه",
    "main": "رئيسي",
    "maintain": "يحافظ",
    "maintenance": "صيانة",
    "majestic": "مهيب",
    "major": "رئيسي",
    "majority": "أغلبية",
    "makeshift": "مؤقت",
    "malady": "مرض",
    "malevolent": "خبيث",
    "malfunction": "عطل",
    "malice": "حقد",
    "malicious": "خبيث",
    "malignant": "خبيث",
    "malleable": "مرن",
    "malpractice": "سوء ممارسة",
    "mammoth": "ضخم",
    "manage": "يدير",
    "mandate": "تفويض",
    "mandatory": "إلزامي",
    "maneuver": "مناورة",
    "mangle": "يشوه",
    "manifest": "يظهر",
    "manipulate": "يتلاعب",
    "manner": "أسلوب",
    "manor": "قصر",
    "manual": "يدوي",
    "manufacture": "يصنع",
    "manuscript": "مخطوطة",
    "many": "كثير",
    "map": "خريطة",
    "mar": "يشوه",
    "marathon": "ماراثون",
    "march": "مسيرة",
    "marginal": "هامشي",
    "marine": "بحري",
    "marital": "زوجي",
    "maritime": "بحري",
    "mark": "علامة",
    "marked": "ملحوظ",
    "market": "سوق",
    "marriage": "زواج",
    "marrow": "نخاع",
    "marry": "يتزوج",
    "marsh": "مستنقع",
    "marshal": "يحشد",
    "martial": "عسكري",
    "martyr": "شهيد",
    "marvel": "عجيبة",
    "marvelous": "رائع",
    "masculine": "ذكوري",
    "mask": "قناع",
    "mass": "كتلة",
    "massacre": "مذبحة",
    "massive": "ضخم",
    "master": "سيد",
    "masterpiece": "تحفة",
    "mastery": "إتقان",
    "match": "مباراة",
    "mate": "رفيق",
    "material": "مادة",
    "maternal": "أمومي",
    "mathematical": "رياضي",
    "matrix": "مصفوفة",
    "matter": "مسألة",
    "mature": "ناضج",
    "maturity": "نضج",
    "maximum": "حد أقصى",
    "maze": "متاهة",
    "meadow": "مرج",
    "meager": "ضئيل",
    "mean": "يعني",
    "meaning": "معنى",
    "meaningful": "ذو معنى",
    "meantime": "في هذه الأثناء",
    "meanwhile": "في غضون ذلك",
    "measurable": "قابل للقياس",
    "measure": "مقياس",
    "mechanic": "ميكانيكي",
    "mechanical": "ميكانيكي",
    "mechanism": "آلية",
    "medal": "ميدالية",
    "meddle": "يتدخل",
    "media": "وسائل إعلام",
    "mediate": "يتوسط",
    "medical": "طبي",
    "medieval": "قروسطي",
    "mediocre": "متوسط",
    "meditate": "يتأمل",
    "medium": "وسط",
    "meek": "وديع",
    "meet": "يلتقي",
    "melancholy": "كآبة",
    "mellow": "ناضج",
    "melodious": "عذب",
    "melody": "لحن",
    "melt": "يذوب",
    "member": "عضو",
    "membrane": "غشاء",
    "memento": "تذكار",
    "memoir": "مذكرات",
    "memorable": "لا يُنسى",
    "memorial": "نصب تذكاري",
    "memorize": "يحفظ",
    "memory": "ذاكرة",
    "menace": "تهديد",
    "mend": "يصلح",
    "menial": "وضيع",
    "mental": "عقلي",
    "mention": "يذكر",
    "mentor": "مرشد",
    "mercenary": "مرتزق",
    "merciful": "رحيم",
    "merciless": "قاسٍ",
    "mercury": "زئبق",
    "mercy": "رحمة",
    "mere": "مجرد",
    "merely": "مجرد",
    "merge": "يندمج",
    "merit": "جدارة",
    "merry": "مرح",
    "mesh": "شبكة",
    "mess": "فوضى",
    "message": "رسالة",
    "messenger": "رسول",
    "metabolic": "استقلابي",
    "metal": "معدن",
    "metamorphosis": "تحول",
    "metaphor": "استعارة",
    "method": "طريقة",
    "methodical": "منهجي",
    "meticulous": "دقيق",
    "metric": "متري",
    "metropolis": "عاصمة",
    "metropolitan": "حضري",
    "microbe": "ميكروب",
    "microscope": "مجهر",
    "microscopic": "مجهري",
    "midday": "ظهر",
    "middle": "وسط",
    "middleman": "وسيط",
    "midnight": "منتصف الليل",
    "midst": "وسط",
    "might": "قد",
    "mighty": "عظيم",
    "migrate": "يهاجر",
    "mild": "معتدل",
    "mildew": "عفن",
    "milestone": "معلم",
    "militant": "مناضل",
    "military": "عسكري",
    "militia": "ميليشيا",
    "mill": "مطحنة",
    "millennium": "ألفية",
    "mimic": "يقلد",
    "mince": "يقطع",
    "mind": "عقل",
    "mindful": "متنبه",
    "mine": "منجم",
    "mineral": "معدن",
    "mingle": "يختلط",
    "miniature": "مصغر",
    "minimal": "أدنى",
    "minimize": "يقلل",
    "minimum": "حد أدنى",
    "mining": "تعدين",
    "minister": "وزير",
    "ministry": "وزارة",
    "minor": "بسيط",
    "minority": "أقلية",
    "mint": "نعناع",
    "minus": "ناقص",
    "minute": "دقيقة",
    "miracle": "معجزة",
    "miraculous": "معجزي",
    "mirage": "سراب",
    "mire": "مستنقع",
    "mirror": "مرآة",
    "mirth": "مرح",
    "miscarriage": "إجهاض",
    "miscellaneous": "متنوع",
    "mischief": "شقاوة",
    "mischievous": "مؤذٍ",
    "misconception": "مفهوم خاطئ",
    "misconduct": "سوء سلوك",
    "misdeed": "جريمة",
    "miser": "بخيل",
    "miserable": "بائس",
    "misfortune": "سوء حظ",
    "misgiving": "شك",
    "misguided": "مضلل",
    "mishap": "حادث",
    "misinform": "يضلل",
    "misinterpret": "يسيء فهم",
    "misjudge": "يسيء الحكم",
    "mislead": "يضلل",
    "misplace": "يضع في مكان خطأ",
    "miss": "يفتقد",
    "missile": "صاروخ",
    "missing": "مفقود",
    "mission": "مهمة",
    "missionary": "مبشر",
    "mist": "ضباب",
    "mistake": "خطأ",
    "mistaken": "مخطئ",
    "mistrust": "عدم ثقة",
    "misty": "ضبابي",
    "misunderstand": "يسيء فهم",
    "misuse": "سوء استخدام",
    "mitigate": "يخفف",
    "mix": "يخلط",
    "mixture": "خليط",
    "moan": "أنين",
    "mob": "غوغاء",
    "mobile": "متحرك",
    "mobilize": "يحشد",
    "mock": "يسخر",
    "mockery": "سخرية",
    "mode": "وضع",
    "model": "نموذج",
    "moderate": "معتدل",
    "modern": "حديث",
    "modernize": "يحدث",
    "modest": "متواضع",
    "modify": "يعدل",
    "modular": "نمطي",
    "module": "وحدة",
    "moist": "رطب",
    "moisture": "رطوبة",
    "mold": "قالب",
    "molecule": "جزيء",
    "molest": "يتحرش",
    "mollify": "يهدئ",
    "molten": "منصهر",
    "moment": "لحظة",
    "momentary": "لحظي",
    "momentous": "مهم",
    "momentum": "زخم",
    "monarch": "ملك",
    "monastery": "دير",
    "monetary": "نقدي",
    "money": "مال",
    "monitor": "يراقب",
    "monk": "راهب",
    "monopolize": "يحتكر",
    "monopoly": "احتكار",
    "monotonous": "رتيب",
    "monster": "وحش",
    "monstrous": "وحشي",
    "month": "شهر",
    "monument": "نصب تذكاري",
    "monumental": "ضخم",
    "mood": "مزاج",
    "moody": "متقلب المزاج",
    "moon": "قمر",
    "moor": "يربط",
    "moot": "مثير للجدل",
    "moral": "أخلاقي",
    "morale": "معنويات",
    "morality": "أخلاق",
    "morass": "مستنقع",
    "morbid": "مرضي",
    "more": "أكثر",
    "moreover": "علاوة على ذلك",
    "morgue": "مشرحة",
    "morning": "صباح",
    "morose": "كئيب",
    "morsel": "لقمة",
    "mortal": "فانٍ",
    "mortality": "وفيات",
    "mortgage": "رهن عقاري",
    "mortify": "يذل",
    "mosaic": "فسيفساء",
    "mosque": "مسجد",
    "mosquito": "بعوضة",
    "moss": "طحلب",
    "most": "معظم",
    "mostly": "معظمه",
    "motel": "فندق صغير",
    "moth": "عثة",
    "mother": "أم",
    "motif": "زخرفة",
    "motion": "حركة",
    "motionless": "بلا حركة",
    "motivate": "يحفز",
    "motive": "دافع",
    "motor": "محرك",
    "motto": "شعار",
    "mound": "تل",
    "mount": "يصعد",
    "mountain": "جبل",
    "mountainous": "جبلي",
    "mourn": "يحزن",
    "mournful": "حزين",
    "mouse": "فأر",
    "mouth": "فم",
    "move": "يتحرك",
    "movement": "حركة",
    "movie": "فيلم",
    "moving": "مؤثر",
    "much": "كثير",
    "muck": "وحل",
    "mud": "طين",
    "muddle": "يرتبك",
    "muddy": "موحل",
    "muffin": "كعكة",
    "muffle": "يكتم",
    "mug": "كوب",
    "muggy": "رطب",
    "mule": "بغل",
    "mull": "يتأمل",
    "multiple": "متعدد",
    "multiply": "يضاعف",
    "multitude": "عدد كبير",
    "mumble": "يتمتم",
    "mummy": "مومياء",
    "municipal": "بلدي",
    "munificent": "كريم",
    "munitions": "ذخيرة",
    "mural": "جداري",
    "murder": "قتل",
    "murderous": "قاتل",
    "murky": "مظلم",
    "murmur": "همس",
    "muscle": "عضلة",
    "muscular": "عضلي",
    "muse": "يتأمل",
    "museum": "متحف",
    "mushroom": "فطر",
    "music": "موسيقى",
    "musical": "موسيقي",
    "musician": "موسيقي",
    "muster": "يحشد",
    "musty": "عفن",
    "mutable": "متغير",
    "mutate": "يتحور",
    "mute": "أخرس",
    "mutilate": "يشوه",
    "mutiny": "تمرد",
    "mutter": "يتمتم",
    "mutual": "متبادل",
    "muzzle": "كمامة",
    "myriad": "لا يحصى",
    "mysterious": "غامض",
    "mystery": "لغز",
    "mystic": "صوفي",
    "mystify": "يحير",
    "myth": "أسطورة",
    "mythical": "أسطوري",
    "mythology": "أساطير",
    
    # Remaining untranslated words (manual completion)
    "aids": "الإيدز",
    "am": "صباحًا",
    "african": "أفريقي",
    "african-american": "أمريكي من أصل أفريقي",
    "american": "أمريكي",
    "arab": "عربي",
    "asian": "آسيوي",
    "bible": "الكتاب المقدس",
    "british": "بريطاني",
    "ceo": "الرئيس التنفيذي",
    "canadian": "كندي",
    "catholic": "كاثوليكي",
    "chinese": "صيني",
    "christian": "مسيحي",
    "christmas": "عيد الميلاد",
    "dna": "الحمض النووي",
    "democrat": "ديمقراطي",
    "english": "إنجليزي",
    "european": "أوروبي",
    "french": "فرنسي",
    "german": "ألماني",
    "god": "الله",
    "i": "أنا",
    "indian": "هندي",
    "iraqi": "عراقي",
    "irish": "أيرلندي",
    "islamic": "إسلامي",
    "israeli": "إسرائيلي",
    "italian": "إيطالي",
    "japanese": "ياباني",
    "jew": "يهودي",
    "jewish": "يهودي",
    "latin": "لاتيني",
    "mexican": "مكسيكي",
    "mr": "السيد",
    "mrs": "السيدة",
    "ms": "السيدة (Ms)",
    "muslim": "مسلم",
    "olympic": "أولمبي",
    "pc": "حاسوب شخصي",
    "pm": "مساءً",
    "palestinian": "فلسطيني",
    "republican": "جمهوري",
    "russian": "روسي",
    "soviet": "سوفيتي",
    "spanish": "إسباني",
    "supreme": "أسمى",
    "tv": "تلفاز",
    "united": "متحد",
    "abortion": "إجهاض",
    "abroad": "في الخارج",
    "absolutely": "بالتأكيد",
    "abuse": "إساءة",
    "accompany": "يرافق",
    "according": "وفقًا",
    "accuse": "يتهم",
    "activist": "ناشط",
    "actually": "في الواقع",
    "ad": "إعلان",
    "addition": "إضافة",
    "adjustment": "تعديل",
    "administrator": "مسؤول",
    "admission": "قبول",
    "advanced": "متقدم",
    "advise": "ينصح",
    "adviser": "مستشار",
    "again": "مرة أخرى",
    "anybody": "أي شخص",
    "apparently": "على ما يبدو",
    "appearance": "مظهر",
    "approximately": "تقريبًا",
    "badly": "بشدة",
    "beneath": "تحت",
    "birthday": "عيد ميلاد",
    "boyfriend": "حبيب",
    "carbon": "كربون",
    "carefully": "بعناية",
    "chairman": "رئيس مجلس الإدارة",
    "childhood": "طفولة",
    "closer": "أقرب",
    "communication": "اتصال",
    "composition": "تركيب",
    "congressional": "خاص بالكونغرس",
    "construction": "بناء",
    "cooking": "طبخ",
    "counter": "عداد",
    "county": "مقاطعة",
    "creation": "إنشاء",
    "creature": "مخلوق",
    "death": "موت",
    "delivery": "توصيل",
    "differently": "بشكل مختلف",
    "disappear": "يختفي",
    "downtown": "وسط المدينة",
    "dramatic": "درامي",
    "dramatically": "بشكل كبير",
    "e-mail": "بريد إلكتروني",
    "educational": "تعليمي",
    "elsewhere": "في مكان آخر",
    "enable": "يمكّن",
    "environmental": "بيئي",
    "essay": "مقال",
    "everybody": "الجميع",
    "everyday": "يومي",
    "everyone": "الجميع",
    "feeling": "شعور",
    "following": "التالي",
    "fourth": "الرابع",
    "friendship": "صداقة",
    "generally": "عمومًا",
    "gentleman": "رجل محترم",
    "girlfriend": "حبيبة",
    "golden": "ذهبي",
    "grain": "حبة",
    "grandfather": "جد",
    "grandmother": "جدة",
    "greatest": "الأعظم",
    "growing": "متزايد",
    "hardly": "بالكاد",
    "healthy": "صحي",
    "helpful": "مفيد",
    "highly": "للغاية",
    "holiday": "عطلة",
    "homeless": "بلا مأوى",
    "household": "أسرة",
    "housing": "إسكان",
    "immediately": "فورًا",
    "increasing": "متزايد",
    "increasingly": "على نحو متزايد",
    "intellectual": "فكري",
    "largely": "إلى حد كبير",
    "lawn": "عشب",
    "learning": "تعلّم",
    "literally": "حرفيًا",
    "lovely": "جميل",
    "lover": "عاشق",
    "maker": "صانع",
    "makeup": "مكياج",
    "nevertheless": "مع ذلك",
    "nobody": "لا أحد",
    "number": "رقم",
    "observer": "مراقب",
    "ongoing": "مستمر",
    "online": "عبر الإنترنت",
    "overcome": "يتغلب",
    "overlook": "يتجاهل",
    "painter": "رسام",
    "pair": "زوج",
    "participant": "مشارك",
    "participate": "يشارك",
    "particular": "معين",
    "particularly": "خاصةً",
    "partly": "جزئيًا",
    "personally": "شخصيًا",
    "personnel": "موظفون",
    "photo": "صورة",
    "photograph": "صورة فوتوغرافية",
    "photographer": "مصور",
    "planning": "تخطيط",
    "politically": "سياسيًا",
    "politician": "سياسي",
    "presidential": "رئاسي",
    "prisoner": "سجين",
    "production": "إنتاج",
    "proof": "دليل",
    "publicly": "علنًا",
    "publisher": "ناشر",
    "quarterback": "لاعب وسط",
    "reasonable": "معقول",
    "regional": "إقليمي",
    "remarkable": "ملحوظ",
    "remind": "يذكر",
    "repeatedly": "مرارًا",
    "romantic": "رومانسي",
    "seat": "مقعد",
    "shape": "شكل",
    "shot": "طلقة",
    "shower": "دُش",
    "sick": "مريض",
    "slowly": "ببطء",
    "somebody": "شخص ما",
    "somewhat": "إلى حد ما",
    "spokesman": "متحدث رسمي",
    "stable": "مستقر",
    "strengthen": "يقوي",
    "strip": "ينزع",
    "strongly": "بقوة",
    "surprising": "مفاجئ",
    "surprisingly": "بشكل مفاجئ",
    "surround": "يحيط",
    "swear": "يقسم",
    "swing": "يتأرجح",
    "tablespoon": "ملعقة طعام",
    "technical": "تقني",
    "telephone": "هاتف",
    "threaten": "يهدد",
    "throughout": "طوال",
    "tonight": "الليلة",
    "toward": "نحو",
    "towards": "نحو",
    "tremendous": "هائل",
    "twin": "توأم",
    "unable": "غير قادر",
    "undergo": "يخضع لـ",
    "unknown": "مجهول",
    "valuable": "ثمين",
    "voter": "ناخب",
    "vulnerable": "ضعيف",
    "war": "حرب",
    "warning": "تحذير",
    "weekend": "عطلة نهاية الأسبوع",
    "weight": "وزن",
    "welcome": "ترحيب",
    "whatever": "أيًّا يكن",
    "whenever": "كلما",
    "whereas": "بينما",
    "winner": "فائز",
    "withdraw": "ينسحب",
    "wooden": "خشبي",
}

def translate_file(filepath):
    """
    Translate all untranslated words in the HTML file.
    """
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Pattern to match untranslated word cards
    pattern = r'<div class="word-card no-translation">\s*<div class="word-english">([^<]+)</div>\s*<div class="word-arabic">\1</div>\s*<span class="placeholder-badge">~</span>\s*</div>'
    
    def replace_word(match):
        english_word = match.group(1).strip()
        # Try to get translation (case-insensitive)
        arabic_translation = TRANSLATIONS.get(english_word.lower(), None)
        
        if arabic_translation:
            # Return translated version
            return f'''<div class="word-card has-translation">
                    <div class="word-english">{english_word}</div>
                    <div class="word-arabic">{arabic_translation}</div>
                    <span class="translation-badge">✓</span>
                </div>'''
        else:
            # Return original (no translation found)
            return match.group(0)
    
    # Perform replacements
    new_content = re.sub(pattern, replace_word, content)
    
    # Save the updated content
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(new_content)
    
    # Count how many translations were made
    original_count = len(re.findall(r'class="word-card no-translation"', content))
    remaining_count = len(re.findall(r'class="word-card no-translation"', new_content))
    translated_count = original_count - remaining_count
    
    return translated_count, remaining_count

if __name__ == "__main__":
    filepath = r"c:\Users\Mostafa\OneDrive\Attachments\MY work\organized_vocabulary.html"
    translated, remaining = translate_file(filepath)
    print(f"Translation complete!")
    print(f"Words translated: {translated}")
    print(f"Words remaining untranslated: {remaining}")
    print(f"\nFile updated: {filepath}")
